/**
 * REAL, finalized card series checklists — the exact published contents of a
 * produced series. Unlike the illustrative EXAMPLE data in card-checklist-data.ts,
 * these are flat, exact lists and are NOT subject to a "contents may vary" caveat.
 */

export type CardSeriesChecklist = {
  id: string;
  title: string;
  subtitle?: string;
  cards: string[];
};

export const CARD_SERIES_CHECKLISTS: CardSeriesChecklist[] = [
  {
    id: 'gauntlet-series-1-2026-07-24',
    title: 'Gauntlet Series 1 7/24/2026',
    subtitle: 'Exact 100-card checklist',
    cards: [
      '2025 topps chrome /99 Tyler Allgeier',
      "2025 topps chrome light speed /75 De'Von Achane",
      '2025 topps finest /20 TreVeyon Henderson',
      '2025 topps cert. auto /150 Courtland Sutton',
      '2025 topps chrome fortune /275 Malik Nabers',
      "2024 panini nat. treasures patch /35 Ja'Tavion Sanders",
      '2025 panini prizm donruss rookie Isaac TeSlaa',
      '2024 panini illusions rookie auto /299 Blake Corum',
      '2025 topps chrome starry nights Saquon Barkley',
      '2025 topps chrome starry nights Joe Burrow',
      '2025 panini contours RJ Harvey',
      '2025 topps chrome blue shimmer Jahmyr Gibbs',
      '2025 topps chrome starry nights Ashton Jeanty',
      '2025 panini optic Uptown Travis Hunter',
      '2024 topps chrome galaxy greats /99 Richard Sherman',
      '2025 panini silo. patch auto /99 Rod Smith',
      '2019 panini chronicles psa 10 Ja Morant',
      '2024 prizm orange ice psa 10 Michael Penix Jr.',
      '2019 panini prizm neon green pulsar psa 9 auto Alex Barnes',
      '1996 ultra decade of excellence psa 8 Michael Jordan',
      '1998 topps chrome seasons best refractor psa 9 Tim Duncan',
      '2024 bowmans best purple mojo psa 10 Aaron Judge',
      '2025 mosaic red camo psa 10 Jaxson Dart',
      '2026 topps bowman chrome auto Jean Carlos',
      '2026 topps bowman chrome auto Jean Carlos',
      '2026 topps finest oil spill Carter Jensen',
      '2026 topps finest personality auto Chris Rose',
      '2026 topps chrome auto Jared Jones',
      '2026 topps chrome auto /125 James Quinn Irons',
      '2024 panini select diamond level /25 Aaron Judge',
      '2025 panini donruss fifa Lionel Messi',
      '2026 topps Trey Gibson',
      '2023 select red disco psa 10 Brandon Miller',
      '2022 prizm draft picks var. purple ice prizm psa 10 Paolo Banchero',
      '2026 topps chrome extra terrestrial /75 Jalen Duren',
      '2026 topps chrome extra terrestrial /50 Chris Paul',
      '2026 topps chrome extra terr /99 Liam McNeeley',
      '2026 topps chrome green planet /75 Nikola Jokic',
      '2026 topps chrome space walk LeBron James',
      '2026 topps chrome extra terr. /75 Naz Reid',
      '2026 topps chrome extra terr. /99 Myles Turner',
      '2026 topps finest oil spill Brady House',
      '2021 panini clearly donruss auto sgc 10 Amon-Ra St. Brown',
      '2026 topps chrome bowman auto Moises Chace',
      '2025 topps finest auto Xavier Worthy',
      '2025 topps cert. auto Quinshon Judkins',
      '2026 topps bowman chrome auto Anderson Araujo',
      '2026 topps bowman chrome auto Andrew Tess',
      '2025 topps chrome red auto /5 Jaylin Williams',
      '2024 panini illusions duo rookie refl. auto Ray Davis & Issac G.',
      '2025 topps cert. signature auto Will Howard',
      '2025 topps finest purple /75 Drake Maye',
      '2024 panini illusions shining stars /99 Brock Purdy',
      '2024 panini illusions /399 Justin Jefferson',
      '2024 panini illusions /75 Terry Bradshaw',
      '2025 topps chrome blue Brian Thomas Jr.',
      '2024 panini illusions abracadabra /199 Jared Goff',
      '2025 panini phoenix color blast Tyler Shough',
      '2024 panini select prizm /81 Jahmyr Gibbs',
      '2025 topps chrome Elic Ayomanor',
      '2025 topps cert. pink /250 Cam Skattebo',
      '2024 panini illusions rc /299 Marvin Harrison',
      '2025 topps finest torcher /10 Tua Tagovailoa',
      '2025 topps cert. /100 rc Trevor Etienne',
      '2025 topps finest purple /99 Jayden Higgins',
      '2023 panini prizm gold shimmer Ray Allen',
      '2026 topps nba hoops LeBron James',
      '2024 panini donruss optic My House! Luka Doncic',
      '2024 panini prizm red Grant Williams',
      '2024 panini donruss optic rookie pink Reed Sheppard',
      '2025 topps chrome /199 Asa Newell',
      '2023 prizm deca dna cert. auto psa 9 Ja Morant',
      '1996 topps psa 9 Allen Iverson',
      '2023 donruss optic purple shock psa 10 rc Jaxon Smith-Njigba',
      '2024 prizm wnba psa 9 Caitlin Clark',
      '2023 prizm green ice psa 9 Bryce Young',
      '2024 panini prizm black /20 Klay Thompson',
      '2021 flawless gold legendary scripts auto /10 Oscar Robertson',
      '2026 topps bowman chrome auto Victor Arias',
      '2026 bowman chrome auto Anderson Araujo',
      '2025 bowman chrome buzz factor auto Braeden Shrewsberry',
      '2023 topps tier one auto /149 Pete Alonso',
      '2025 topps pirates /25 Paul Skenes',
      '2023 bowman chrome M/B psa 10 Spencer Jones',
      '2026 topps chrome auto Nick Monistere',
      '2023 panini prizm ufc Colby Covington',
      '2026 topps bowman chrome purple auto /250 Victor Arias',
      '2026 panini prizm fifa Alter Ego Luka Modric',
      '2026 topps finest auto /50 Jose Reyes',
      '2025 topps chrome starry nights Saquon Barkley',
      '2026 topps blue /150 Freddie Freeman',
      '2026 topps bowman chrome auto Ricardo Cova',
      '2025 topps cert. auto Quinshon Judkins',
      '2025 topps cert. auto rc Jaxon Dart',
      '2025 topps finest auto /99 Savion Williams',
      '2025 topps finest auto /99 Jalen Royals',
      '2025 panini donruss rr auto Dylan Sampson',
      '2024 panini prizm black prolific auto Jared McCain',
      '2024 optic holo auto Reed Sheppard',
      '2025 topps cert. auto rc Will Howard',
    ],
  },
  {
    id: 'gauntlet-live',
    title: 'Gauntlet Live Series 1 7/23/2026',
    subtitle: 'Exact 100-card checklist',
    cards: [
      '1991 Topps auto /25 Scott Rolen',
      '2005 SP Authentic Michael Jordan PSA 9',
      '2017 Panini mosaic prizm auto /25 Karl-Anthony Towns',
      '2018 Panini Prizm Anfernee Simons Silver Prizm PSA 9',
      '2019 Bowman chrome draft Gunnar Henderson refractor sgc 10',
      '2019 Topps Bowman chrome auto Alejandro Kirk',
      '2020 Panini mosaic finals mvp Kevin Durant',
      '2020 Panini select CeeDee Lamb cut white prizm psa 9',
      '2020 Panini select sparks sig tri color prizm auto /49 psa 8 Jonathan Hernandez',
      '2021 Panini donruss optic Jaylen Waddle',
      '2021 Panini prizm UFC purple prizm psa 9 Holly Holm',
      '2021 Panini recon auto /5 Tyrese Maxey',
      '2022 Panini national treasures patch auto /99 Skyy Moore',
      '2022 Panini one precision auto Ahmad “Sauce” Gardner',
      '2022 Panini prizm draft picks Keegan Murray',
      '2022 Panini sensational sign. Auto Jaden Hardy',
      '2023 Panini donruss /99 Michael Porter Jr.',
      '2023 Panini donruss optic mythical Stefon Diggs',
      '2023 Panini select Keyonte George',
      '2024 Caitlin Clark collection donruss gold psa 9',
      '2024 prizm WNBA Caitlin Clark psa 9',
      '2024 donruss Panini psa 10 Tyreek Hill',
      '2024 Panini contenders optic rookie ticket Ricky Pearsall',
      '2024 Panini crown royale Kaboom Pau Gasol',
      '2024 Panini illusions /10 game magicians Dak Prescott',
      '2024 Panini select patch Alexandre Sarr',
      '2024 select prizm /49 Jayson Tatum',
      '2025 Bowman best univ. best of 2025 auto blue refr. psa 10 Kaidon Salter',
      '2025 Panini auto /99 Keyonte George',
      '2025 Bowman crystallized psa 10 Coby Mayo',
      '2025 chrome /10 Brooks Barnhizer',
      '2025 mosaic stained glass Cam Ward',
      '2025 Panini color blast Jalen Milroe',
      '2025 Panini donruss downtown Archie Manning',
      '2025 Panini donruss rookie Mason Taylor',
      '2025 Panini donruss rookie Travis Hunter',
      '2025 Panini impeccable rookie auto /49 Savion Williams',
      '2025 Panini mosaic prizm kaleidoscopic Puka Nacua',
      '2025 Panini rookie Omarion Hampton auto',
      '2025 Panini select Josh Allen',
      '2025 prizm draft picks purple ice psa 9 Arch Manning',
      '2025 Topps auto /225 Michael Pittman Jr.',
      '2025 Topps Bowman /99 Xavian Lee',
      '2025 Topps Bowman chrome gold /75 Pharrel Payne',
      '2025 Topps cert. auto Kaleb Johnson',
      '2025 Topps chrome /199 Dillon Brooks',
      '2025 Topps chrome /199 blue Justin Herbert',
      '2025 Topps chrome /25 Oso Ighodaro',
      '2025 Topps chrome /275 Bradley Beal',
      '2025 Topps chrome /275 Kristaps Porzingis',
      '2025 Topps chrome /50 Kaleb Johnson',
      '2025 Topps chrome /50 gold Cam Whitmore',
      '2025 Topps chrome /75 Collin Sexton',
      '2025 Topps chrome /75 Nick Smith Jr.',
      '2025 Topps chrome /75 extra terrestrial Breece Hall',
      '2025 Topps chrome LeBron James',
      '2025 Topps chrome Saquon Barkley',
      '2025 Topps chrome auto Omarion Hampton',
      '2025 Topps chrome auto /150 Aaron Nesmith',
      '2025 Topps chrome auto /150 Sarah Strong',
      '2025 Topps chrome auto /275 RJ Harvey',
      '2025 Topps chrome auto /50 Jayden Higgins',
      '2025 Topps chrome auto /50 Keon Coleman',
      '2025 Topps chrome auto Devin Carter',
      '2025 Topps chrome auto Will Richard',
      '2025 Topps chrome painted Dylan Harper',
      '2025 Topps chrome pink /250 George Kittle',
      '2025 Topps chrome starry nights Pat Surtain II',
      '2025 Topps chrome starry nights Tetairoa McMillan',
      '2025 Topps chrome urban legends Drake London',
      '2025 Topps chrome urban legends Jordan Love',
      '2025 Topps dual auto /25 Mark Fletcher Jr. & Carson Beck',
      '2025 Topps fanatical Travis Kelce',
      '2025 Topps fearless fighters auto /299 Brian Ortega',
      '2025 Topps finest /150 Luther Burden III',
      '2025 Topps finest /75 Sam LaPorta',
      '2025 Topps finest auto RJ Harvey',
      '2025 Topps finest flashback auto Ladd McConkey',
      '2025 Topps finest greats auto /99 Justin Tuck',
      '2025 Topps finest greats auto Vernon Davis',
      '2025 Topps finest reflash /50 Jared Verse',
      '2025 Topps finest refractor auto Tyler Warren',
      '2025 Topps rookie Cooper Flagg',
      '2026 Panini prizm /40 Santiago Gimenez',
      '2026 Panini prizm /94 Nicolas Tagliafico',
      '2026 Panini prizm auto Bernd Schneider',
      '2026 Panini prizm FIFA /86 Virgil van Dijk',
      '2026 Panini prizm FIFA /94 Ousmane Dembele',
      '2026 Panini prizm FIFA Emiliano Martinez',
      '2026 Panini prizm FIFA Ferran Torres',
      '2026 Panini prizm FIFA Miroslav Klose',
      '2026 Panini prizm FIFA auto /99 Federico Valverde',
      '2026 Topps chrome featherweight auto /25 Brian Ortega',
      '2026 Topps finest /150 Shaquille O’Neal',
      '2026 Topps finest /200 purple Anthony Davis',
      '2026 Topps home field Christian Moore',
      '2026 Topps midnight UFC auto Rose Namajunas',
      '2026 Topps rookie sign. Auto Joan Beringer',
      'JJ McCarthy stained glass psa 9',
      'Paul O’Neill Topps chrome black auto /150',
    ],
  },
  {
    id: 'gauntlet-live-series-2',
    title: 'Gauntlet Live Series 2 7/23/2026',
    subtitle: 'Exact 75-card checklist',
    cards: [
      '1986 donruss rookies Barry Bonds psa 9',
      '1989 Hoops Michael Jordan psa 9',
      '2000 Topps chrome power players refr. Jose Canseco psa 9',
      '2004 fleer auto /100 Ryan Howard',
      '2012 gridiron gems rookie /49 Mohamed Sanu',
      '2017 Panini donruss optic red/yellow psa 10 Donovan Mitchell',
      '2017 Panini donruss optic red/yellow psa 10 Lonzo Ball',
      '2018 Panini donruss press proof silver psa 9 Michael Porter Jr.',
      '2019 Panini mosaic reactive orange psa 9 Giannis Antetokounmpo',
      '2019 Panini prizm orange ice psa 9 Giannis Antetokounmpo',
      '2020 merlin chrome ucl u23 stars psa 10 Eduardo Camavinga',
      '2020 Panini chronicles classics psa 9 Justin Herbert',
      '2020 Panini prizm DP auto psa 10 Anthony McFarland Jr.',
      '2020 Panini prizm auto psa 9 Tony Jones Jr.',
      '2020 Panini prizm Joe Burrow',
      '2020 Panini prizm psa 7 Anthony Edwards',
      '2020 Panini select die cut purple prizm psa 9 Tua Tagovailoa',
      '2021 prizm draft picks green prizm psa 9 Mac Jones',
      '2021 prizm draft picks psa 9 all americans Kadarius Toney',
      '2021 prizm draft picks red white blue prizm psa 8 Najee Harris',
      '2021 prizm red wave auto /149 Elijah Moore',
      '2021 white mosaic psa 10 Alperen Sengun',
      '2023 donruss optic psa 9 Victor Wembanyama',
      '2023 Panini auto /10 TJ Dillashaw',
      '2023 Panini rookie Josh Minott',
      '2023 select tectonic psa 9 Brandon Miller',
      '2023 Topps all aces Shohei Ohtani',
      '2024 prizm Caitlin Clark kaleidoscopic psa 9',
      '2024 Panini donruss optic sign series auto Jaden Hardy',
      '2024 Panini immaculate coll. Sneaker /49 Rob Dillingham',
      '2024 Panini mosaic auto Dillon Jones',
      '2024 Topps chrome rookie auto psa/dna cert. Wyatt Langford psa 10',
      '2025 Topps chrome starry nights Myles Garrett',
      '2025 Panini Mosaic Football Shedeur Sanders',
      '2025 Topps Chrome VJ Edgecombe x-fractor psa 8',
      '2025 Panini donruss downtown Matthew Golden',
      '2025 Panini prizm Colston Loveland',
      '2025 Panini select Cam Ward',
      '2025 Panini select Nick Emmanwori',
      '2025 Panini select Shedeur Sanders',
      '2025 Panini select zebra Jayden Higgins',
      '2025 Panini stars Omarion Hampton',
      '2025 Topps /150 Bijan Robinson',
      '2025 Topps 1990 relic memorabilia 35 anniv. George Springer',
      '2025 Topps 5 star pentamerous penmanship auto /25 Mark Teixeira',
      '2025 Topps Devin Booker anime',
      '2025 Topps auto Ayla McDowell',
      '2025 Topps Bowman chrome /25 Deniya Prawl',
      '2025 Topps Bowman chrome auto Coen Carr',
      '2025 Topps chrome /150 greatest loading Cedric Coward',
      '2025 Topps chrome /50 Joan Beringer',
      '2025 Topps chrome Ace Bailey',
      '2025 Topps chrome Ashton Jeanty',
      '2025 Topps chrome Cooper Flagg',
      '2025 Topps chrome Jeremy Ruckert',
      '2025 Topps chrome Kon Knueppel',
      '2025 Topps chrome Noa Essengue',
      '2025 Topps chrome Yang Hansen',
      '2025 Topps chrome auto Kel’el Ware',
      '2025 Topps chrome camo Calvin Ridley',
      '2025 Topps chrome fortune Ashton Jeanty',
      '2025 Topps chrome purple refractor psa 8 Tyrese Proctor',
      '2025 Topps chrome starry night CeeDee Lamb',
      '2025 Topps chrome starry nights Cam Ward',
      '2025 Topps chrome starry nights Emeka Egbuka',
      '2025 Topps chrome starry nights Ja’Marr Chase',
      '2025 Topps finest auto Chase Brown',
      '2025 Topps finest auto Mason Miller',
      '2025 Topps finest auto Riley Leonard',
      '2025 Topps finest greats auto /99 Darren Sproles',
      '2025 Topps rookie horiz. Midnight auto Asa Newell',
      '2026 Panini prizm FIFA Mohamed Salah',
      '2026 Topps chrome /175 Karl-Anthony Towns',
      '2026 Topps chrome /250 Charles Oliveira',
      '2026 Topps worlds finest Clayton Kershaw',
    ],
  },
];
