/**
 * REAL, finalized card series checklists — the exact published contents of a
 * produced series. Unlike the illustrative EXAMPLE data in card-checklist-data.ts,
 * these are flat, exact lists and are NOT subject to a "contents may vary" caveat.
 */

export type CardSeriesChecklist = {
  id: string;
  title: string;
  subtitle?: string;
  /** Series type, e.g. 'Gauntlet', 'Nova', 'Fusion', 'Blitz'. */
  seriesType: string;
  /** Publish date in ISO form (YYYY-MM-DD); drives the date buttons on the Cards tab. */
  date: string;
  cards: string[];
};

export type CardSeriesDateGroup = {
  date: string;
  series: CardSeriesChecklist[];
};

/** Groups checklists by publish date, most recent date first. Within a date,
 *  series keep the order they appear in CARD_SERIES_CHECKLISTS. */
export function groupCardSeriesByDate(): CardSeriesDateGroup[] {
  const groups: CardSeriesDateGroup[] = [];
  for (const series of CARD_SERIES_CHECKLISTS) {
    let group = groups.find((g) => g.date === series.date);
    if (!group) {
      group = { date: series.date, series: [] };
      groups.push(group);
    }
    group.series.push(series);
  }
  return groups.sort((a, b) => b.date.localeCompare(a.date));
}

export const CARD_SERIES_CHECKLISTS: CardSeriesChecklist[] = [
  {
    id: 'gauntlet-series-3-2026-08-04',
    title: 'Gauntlet Series 3 8/4/2026',
    subtitle: 'Exact 150-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-08-04',
    cards: [
      '1989 Topps Finest Frank Thomas Auto /29',
      '1994 Topps Stadium Club Michael Jordan',
      '2015-16 Panini Prizm All-Star /350 Kyrie Irving',
      '2018-19 Panini Prizm Brook Lopez Auto',
      '2021-22 Panini Contenders Optic Legendary Tandems Clyde Drexler / Hakeem Olajuwon',
      '2022-23 Panini Donruss Optic Rated Rookie /49 Jaylin Williams',
      '2022-23 Panini Hoops Ja Morant',
      '2022-23 Panini Mosaic Green and Blue Stephen Curry',
      '2022-23 Panini Recon Auto /99 Anfernee Simons',
      '2025-26 Panini Prizm John Stockton',
      '2004 Topps Chrome Philip Rivers PSA 10',
      '2005 Upper Deck Auto /89 Nate Burleson',
      '2007 Upper Deck Premier Penmanship Auto /99 Jason Campbell',
      '2007-08 Topps Finest Rookie /539 Al Horford',
      '2013 Panini Prizm Blidi Wreh-Wilson Auto',
      '2014 Panini National Convention Johnny Manziel BGS Authentic',
      "2014 Panini Prizm Auto /35 Ka'Deem Carey",
      '2014-15 Panini Prizm /139 Kyrie Irving',
      '2015 Panini Certified Potential Auto /50 Denzel Perryman',
      "2015 Panini Crown Royale Da'Ron Brown Auto",
      '2016 Panini Origins Mike Gesicki Patch Auto',
      '2016 Panini Contenders Draft Picks Max Tuerk Auto',
      '2016-17 Panini Donruss Optic Hall Kings /199 Kevin McHale',
      '2016-17 Panini Grand Reserve Auto /99 Alec Burks',
      '2017 Panini Preferred Signatures Patch Auto /199 Jeremy McNichols',
      '2017 Panini Donruss Optic Blue Cooper Kupp PSA 10',
      '2018 Panini Contenders Championship Ticket Auto /25 Dante Pettis',
      '2018 Panini Rookies and Stars Sam Darnold',
      '2018 Contenders Draft Picks Game Day Ticket Sam Darnold PSA 10',
      '2018 Panini Donruss Optic Baker Mayfield PSA 10',
      '2018 Panini Donruss Josh Allen SGC 9',
      '2019 Panini Donruss Optic Jordan Poole PSA 10',
      '2019 Panini Mosaic Zion Williamson PSA 10',
      '2019 Panini Elite Extra Edition Prospect Materials Patch /199 Bobby Dalbec',
      '2019 Panini Mosaic Ja Morant PSA 10',
      '2019 Panini Prizm Draft Picks Zion Williamson PSA 8',
      '2019 Panini Prizm Zion Williamson PSA 10',
      '2019 Panini Prizm Draft Picks Aaron Schunk Auto',
      '2019 Panini Select Silver Prizm Darius Slayton PSA 10',
      '2019 Topps Auto /99 Jose Azocar',
      '2019 Hoops Premium Stock Silver Prizm Zion Williamson PSA 10',
      '2019 Topps Chrome X-Fractor Vladimir Guerrero Jr. PSA 10',
      '2019-20 Panini Status Symbols Dwyane Wade',
      '2019-20 Panini Illusions Anthony Davis',
      '2020 Bowman Chrome Mega Box Auto Glenallen Hill Jr. PSA 10',
      '2020 Mosaic Anthony Edwards Gem Mint 10',
      '2020 Panini Chronicles Jalen Hurts Gem Mint 10',
      '2020 Panini Chronicles Joe Burrow PSA 10',
      '2020 Panini Chronicles Gridiron Kings Joe Burrow PSA 10',
      '2020 Panini Chronicles Luminance Joe Burrow PSA 10',
      '2020 Panini Chronicles Prestige Joe Burrow PSA 10',
      '2020 Panini Chronicles Luminance Pink Justin Herbert PSA 10',
      '2020 Panini Mosaic Justin Jefferson PSA 9',
      '2020 Panini Mosaic Scripts Quenton Nelson Auto',
      '2020 Panini Prizm Draft Picks Justin Jefferson',
      '2020 Panini Select Joe Burrow PSA 10',
      '2020 Panini Select Joe Burrow PSA 10',
      '2020 Panini Select Joe Burrow PSA 10',
      '2020 Panini Select Turbocharged Tom Brady',
      '2020 Panini Prizm RC Auto Theo Maledon',
      '2020 Panini Select Silver Prizm Jordan Love PSA 10',
      '2020-21 Panini Donruss Jersey Series Andrew Wiggins Patch',
      '2020-21 Panini Prizm Mosaic Rookie Auto Cole Anthony',
      '2020-21 Career Lineage Kevin Durant',
      '2021 Bowman Prospects Orange Anthony Volpe BGS 9.5',
      '2021 Panini Certified Rookie Roll Call Auto /35 Davis Mills',
      '2021 Panini Mosaic Man of the Year Kurt Warner',
      '2021 Prizm Silver Prizm Ja Morant PSA 10',
      '2021 Topps Bryan Ramos Auto',
      '2021 Topps Inception Prospect Auto /400 Misael Urbina',
      '2021 Leaf Trinity Auto /50 Elijah Mitchell',
      '2021 Panini Absolute Rookie Premiere Auto /99 Jaylen Waddle',
      '2021-22 Panini Prizm /150 Hakeem Olajuwon',
      '2021-22 My House! LaMelo Ball',
      '2022 Crown Royale Auto /199 Jabari Smith Jr.',
      "2022 Donruss Optic Wave Wan'Dale Robinson PSA 10",
      '2022 Panini Select Rookie Auto /25 Ryan Vilade',
      '2022 Panini Silhouettes Owen Murphy Auto',
      '2022 Mosaic Red/Green Choice George Pickens PSA 10',
      '2022 Panini Mosaic Silver Brock Purdy PSA 10',
      '2022-23 Panini Prizm Purple /75 Ben Wallace',
      "2023 Donruss Press Proof Blue De'Von Achane PSA 10",
      '2023 Donruss Optic Blue Hyper Anthony Richardson PSA 10',
      '2023 Optic Lime Green Puka Nacua PSA 9',
      '2023 Panini James Cook Auto',
      '2023 Panini Contenders Rookie Ticket Nick Hampton Auto',
      '2023 Panini Illusions Bryce Young',
      '2023 Panini Prizm Chase Brown',
      '2023 Panini Signature Series Tony Mandarich Auto',
      '2023 Panini Prizm Auto /25 Will Anderson Jr.',
      '2023 Prestige CJ Stroud PSA 10',
      '2023 Prizm Silver Prizm Scoot Henderson PSA 9',
      '2023-24 Panini Donruss Kit Kings Aurelien Tchouameni Patch',
      '2024 Panini Donruss Elite Blue /99 Spencer Rattler',
      '2024 Panini Mosaic Jordan Morgan Auto',
      '2024 Panini Zenith Z-Jersey Bo Nix Patch',
      '2024 Panini Contenders Rookie Ticket Dallas Turner Auto',
      '2024 Panini Prestige Gabriel Murphy Auto',
      '2024 Panini Select Auto /49 Laiatu Latu',
      '2024 Topps Chrome Black Base Auto Matt Mervis',
      '2024 Topps Chrome Certified Auto /50 Gary Trent Jr.',
      '2024 Topps Chrome James Harrison',
      '2024 Topps Chrome Auto Variation /99 Maason Smith',
      '2024 Topps Finest Auto /50 Irene Aldana',
      '2024 Topps Finest Greats Auto /25 Delanie Walker',
      '2024 Topps Midnight Horizon Signatures Auto /199 Evan Fournier',
      '2024 Topps Now Jayden Daniels PSA 10',
      '2024 Topps Inception Rookie Auto /125 Devontez Walker',
      '2024 Panini Prizm Blue Wave J.J. McCarthy PSA 10',
      '2024 Panini Select Purple Prizm J.J. McCarthy PSA 10',
      '2024 Panini Significant Signatures Quincy Williams Auto',
      '2024 Prizm Green Prizm Caitlin Clark PSA 9',
      '2024 Prizm Disco Bo Nix PSA 10',
      '2024 Prizm Orange Ice Caitlin Clark PSA 9',
      '2024 Topps Inception Rookie Auto Jonathon Brooks',
      '2024 Topps Certified Five Star Auto /15 Ichiro',
      '2024 Topps Midnight Ahman Green Auto',
      '2024-25 Panini Prizm Black Sensational Signatures P.J. Washington Jr. Auto',
      '2024-25 Donruss Optic Pink Klay Thompson',
      '2024-25 Panini Donruss Optic Stephen Curry',
      '2024-25 Panini Mosaic Scripts Jordan Goodwin Auto',
      '2024-25 Panini Revolution Cam Christie Auto',
      '2024-25 Panini Signature Selections Jaden Hardy',
      '2025 Panini Phoenix Thunderbirds /299 Emeka Egbuka',
      '2025 Panini RC Auto /49 Donovan Ezeiruaku',
      '2025 Panini VIP Rookie VJ Edgecombe',
      '2025 Panini Mosaic Jaxson Dart',
      '2025 Panini Mosaic Candy Cane Terrence Ferguson',
      '2025 Panini Prizm Patrick Mahomes',
      '2025 Panini Prizm Draft Picks Sensational Signature Danny Gray',
      '2025 Topps Auto /150 Pedro Leon',
      '2025 Topps Woven Wonder Relics Brandon Miller Patch',
      '2025 Topps Chrome Purple Auto /299 Stuart Berroa',
      '2025 Topps Finest Tyleik Williams Auto',
      '2025 Topps Finest Rookies Jean Matsumoto Auto',
      '2025 Bowman Chrome Prospect Auto Charlie Condon PSA 9',
      '2025 Bowman Chrome Sapphire Prospect Yellow Nick Kurtz PSA 9',
      '2025 Donruss Elite Green Disco Cam Skattebo PSA 10',
      "2025 Panini Mosaic Rookie Scripts Sai'vion Jones Auto",
      '2025 Topps Certified Refractor Cam Skattebo',
      '2025 Topps Finest Refractor Quinnen Williams Auto',
      '2026 Panini Prizm FIFA World Cup Raphinha',
      '2026 Panini Prizm FIFA World Cup Vini Jr.',
      '2026 Panini Prizm World Cup Lionel Messi',
      '2026 Topps /75 Julian Alvarez',
      '2026 Topps Chrome Purple Auto /250 James Quinn Irons',
      '2026 Topps Inception Luguentz Dort',
      '2026 Topps NBA Hoops Shai Gilgeous-Alexander',
      '2026 Topps Chrome 75 Years Auto /299 Jacob Melton',
      '2026 Topps Inception /125 Tyler Herro',
    ],
  },
  {
    id: 'gauntlet-series-1-2026-08-03',
    title: 'Gauntlet Series 1 8/3/2026',
    subtitle: 'Exact 150-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-08-03',
    cards: [
      '1988 Fleer Dennis Rodman PSA 9',
      '1991 Kayo Lennox Lewis',
      '1996 All Sport PPF Kobe Bryant PSA 8',
      '1996 Score Board All Sport PPF Kobe Bryant',
      '1996 Score Board Kobe Bryant',
      '1996-97 Score Board Stephon Marbury Auto',
      '1997 Topps Chrome Tracy McGrady PSA 10',
      '1997-98 Upper Deck Crunch Time Kobe Bryant',
      '1999 Upper Deck Chirography Auto Mark Mulder',
      '2000 Bowman Chrome Brian Urlacher PSA 10',
      '2000 Fleer Vince Carter',
      '2003 Roberto Alomar Patch /150',
      '2003 Topps Tribute Sammy Sosa',
      '2003 Upper Deck Terrell Suggs Auto',
      '2003 Upper Deck Signature Series Horace Clarke Auto',
      '2005 Topps Nate Burleson Auto',
      '2006 Legends Ron McDole Auto',
      '2006 Ultimate Signature Auto /25 Larry Johnson',
      '2008 Topps Moments & Milestones Derek Jeter',
      '2011 Panini Certified Patch /250 Delone Carter',
      '2011 Bowman Chrome Mike Trout PSA 9',
      '2012 Bowman Chrome Prospects Blue Refractor Bryce Harper BGS 9.5',
      '2012-13 Baron Davis Patch /99',
      '2014 Panini Prizm Mike Trout',
      '2014 Topps Rookie Jumbo Relic Patch /75 Marqise Lee',
      '2015 Panini Contenders Rookie Ticket Patch Karlos Williams',
      '2015 Topps Rookie Patch Auto /25 Mike Davis',
      '2016 Bowman Inception Auto /99 Orlando Arcia BGS 9',
      "2017 Bowman's Best Top Prospects Vladimir Guerrero Jr. PSA 10",
      '2017-18 Panini Chronicles Patch Auto /199 Josh Jackson',
      '2017-18 Panini Crown Royale Auto /99 Rick Fox',
      '2018 Panini Contenders Optic Rookie Ticket Auto Nick Chubb',
      '2018 Panini Donruss Elite /699 Mike Gesicki PSA 10',
      '2018 Panini Donruss Optic Stephen Curry',
      '2018 Panini Prizm Disco Baker Mayfield Gem Mint 9.5',
      '2018 Topps Tim Howard Patch /95',
      "2018-19 Panini Crown Royale Patch De'Anthony Melton",
      '2018-19 Panini Prizm LeBron James',
      '2019 Panini Prizm Purple /49 Terrell Davis',
      "2019 Panini Prizm Lil'Jordan Humphrey Auto",
      '2019-20 Panini Hoops Premium Julius Erving',
      '2020 Bowman Sterling Prospects Julio Rodriguez SGC 10',
      '2020 Panini Chronicles Clear Vision Rookies Joe Burrow PSA 10',
      '2020 Panini Chronicles Legacy Joe Burrow Gem Mint 10',
      '2020 Panini Chronicles Joe Burrow PSA 10',
      '2020 Panini Chronicles Playoff Momentum Rookies Joe Burrow',
      '2020 Panini Prizm Red Ice Ja Morant',
      "2020 Panini Prizm Auto /99 K'Lavon Chaisson",
      '2020 Bowman Chrome Prospect Auto Speckle Refractor Anthony Volpe PSA 10',
      "2020 Panini Score Artist's Proof /35 Danielle Hunter",
      '2020 Topps Nolan Gorman Auto',
      '2020 Topps Pro Debut Ezequiel Tovar Auto',
      '2020-21 Immaculate Patch /25 Kemba Walker',
      '2020-21 Panini Contenders Rookie Auto Caleb Martin',
      '2020-21 Panini Donruss Express Lane',
      '2020-21 Panini Donruss Signature Series Auto Alex Caruso',
      '2020-21 Panini Prizm Instant Impact Anthony Edwards',
      '2021 Bowman Chrome M/B Bobby Witt Jr. PSA 9',
      '2021 Leaf Trinity Auto /25 Tyler Vaughn',
      '2021 Panini Contenders Optic Illusion Tom Brady',
      "2021 Panini Rookies & Stars Dress for Success Auto /25 Ja'Marr Chase",
      '2021-22 Panini Chronicles Threads Franz Wagner',
      '2022 Panini Elite Extra Edition Andrew Pintar Auto',
      '2022 Panini Legacy Auto /99 Romeo Doubs',
      '2022 Panini Prizm Malik Willis Patch',
      '2022 Panini Patch Auto /99 Travon Walker',
      '2022 Panini Zenith Behind the Numbers Tom Brady',
      '2022 Panini Player of the Day /99 Micah Parsons',
      "2022 Topps Travis d'Arnaud Patch /50",
      '2022 Panini Contenders The Finals Auto /49 Jalen Williams',
      '2022 Topps Bowman Auto /99',
      '2023 Leaf Rookie Auto /6 Isaiah Foskey',
      '2023 Panini Contenders Rookie Ticket Patch Michael Mayer',
      '2023 Panini Illusions First Impressions Auto /399 Roschon Johnson',
      '2023 Select Rookie Jumbo Swatch Jackson Holliday PSA 10',
      '2023 Topps 1st Bowman Drake Maye UNC',
      '2023 Topps Auto /299 George Kirby',
      '2023 Topps Museum Patch /25 Korey Lee',
      '2023 Topps Auto /199 Nelson Velazquez',
      '2023 Select Score Throwback Tie-Dye Prizm Garrett Wilson PSA 8',
      '2023 Topps Tier One Break Out Auto /249 Corbin Carroll PSA 10',
      '2023-24 Panini Contenders Auto /25 Onyeka Okongwu',
      '2023-24 Panini Mosaic Montage LeBron James BGS 9',
      '2023-24 Panini Prizm Dariq Whitehead',
      '2023-24 Panini Revolution /125 Rudy Gobert',
      '2023-24 Panini Select Austin Reaves',
      '2023-24 Panini Select /249 Zion Williamson',
      '2024 Allen & Ginter Relic B Mike Trout PSA 10',
      '2024 Donruss Optic Pink Rome Odunze PSA 8',
      '2024 Donruss Rated Rookie Retro Michael Penix Jr.',
      '2024 Panini Draft Picks Chris Braswell Auto',
      '2024 Panini Lionel Messi',
      '2024 Panini Prizmatic J.J. McCarthy',
      '2024 Panini Rookie Contenders Andrew Coker Auto',
      '2024 Panini Rookie Premiere /99 Dallas Turner',
      '2024 Topps Museum Triple Patch Auto /299 Alek Thomas',
      '2024 Topps Now Jayden Daniels',
      '2024 Bowman U Chrome Red Shimmer Ryan Williams PSA 8',
      '2024 Disney Lorcana EN 5 Enchanted Clarabelle PSA 9',
      '2024 Panini Phoenix Contours Bronze Bo Nix PSA 10',
      '2024 Prizm Deca Brilliance Silver Prizm Bo Nix PSA 8',
      '2024 Select Copper Shock Prizm Joe Burrow BGS 9.5',
      '2024-25 Panini Obsidian Anfernee Simons',
      '2024-25 Panini Prizm Black Marcus Smart Auto',
      '2024-25 Panini Patch Donovan Clingan',
      '2024-25 Topps Finest Bruce Brown Jr. Auto',
      '2024-25 Topps Inception Patch /75 Jalen Green',
      '2024-25 Topps Inception Auto /99 Isaiah Hartenstein',
      '2025 Bowman Chrome Prospect Auto Michael Taaffe',
      '2025 Panini Donruss Optic Aqua Calvin Johnson',
      '2025 Panini Donruss Optic Patch /25 Elijah Arroyo',
      '2025 Panini Donruss Optic /299 Jordan Watkins',
      '2025 Panini Donruss Will Shipley Auto',
      '2025 Panini Donruss Optic Green Shedeur Sanders',
      '2025 Panini Mosaic Orange /199 Tiki Barber',
      '2025 Panini Phoenix Paragon Jaxson Dart',
      '2025 Panini Prizm Draft Tre Harris Auto',
      '2025 Panini Prizm Fireworks Travis Hunter',
      '2025 Panini Select Blue /249 Shedeur Sanders',
      '2025 Panini Absolute Legends Auto /25 Rodney Hampton',
      '2025 Panini Select Rookie Swatches Patch Cam Skattebo',
      '2025 Topps Cooper Flagg PSA 10',
      '2025 Upper Deck Tiger Woods',
      '2025 Topps /50 Anfernee Simons',
      '2025 Topps Chrome Kon Knueppel',
      '2025 Topps Cosmic White SSP',
      "2025 Topps Auto /99 De'Andre Hunter",
      '2025 Topps Purple Auto /299 Duke Ellis',
      '2025 Topps Leather Emeka Egbuka',
      '2025 Topps Finest Auto /99 Adam Mazur',
      '2025 Topps Now Shohei Ohtani',
      '2025 Topps Rip Night Dylan Harper',
      '2025 Topps Blue Wave /150 RJ Harvey',
      '2025 National Treasures Rookie Material Auto Quad-Holo Silver Jalen Royals',
      '2025 Panini Mosaic Blue /99 Jayden Daniels',
      '2025 Panini Donruss Optic Patch Shedeur Sanders',
      '2025 Panini Donruss Rated Rookie Auto Travis Hunter',
      '2025 Panini Immaculate Collection Auto /99 Josh Jacobs',
      '2025 Panini Phoenix Auto /20 Cam Skattebo',
      '2025 Prizm Prizmatic Blue Ice /99 Tyler Shough PSA 10',
      '2025 Topps Chrome Pink /350 Kevin Garnett',
      '2025 Topps Chrome Champion Auto /100 Jorge Posada',
      '2025 Topps Clutch City Prospects VJ Edgecombe',
      '2025 Topps Silver Pack Don Mattingly PSA 10',
      '2026 Topps Chrome Auto /76 Haley Winn',
      '2026 Topps Finest Auto /109 Logan Henderson',
      '2026 Topps NBA Hoops Luka Doncic',
      '2026 Topps NBA VJ Edgecombe',
      '2026 Topps Tier One Auto /99 Sal Frelick',
      'Immaculate Patch /49 Brett Phillips',
    ],
  },
  {
    id: 'gauntlet-series-2-2026-08-03',
    title: 'Gauntlet Series 2 8/3/2026',
    subtitle: 'Exact 150-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-08-03',
    cards: [
      '1978 Topps Kareem Abdul-Jabbar PSA 8',
      "1992 Ultra Rookie Shaquille O'Neal PSA 9",
      '1994 Stadium Club Frequent Scorer Points Upgrades Dan Marino PSA 8',
      '1998 Finest Peyton Manning PSA 10',
      '1998 Metal Universe Peyton Manning CGC 9.5',
      "1999 Bowman's Best Rookie /400 David Boston",
      '1999 Sports Illustrated Autograph Collection Darrell Evans',
      '2000 Bowman Chrome Gold Refractor Magglio Ordonez PSA 9',
      '2002 Topps Rick Fox Patch',
      '2004 Donruss Rookie Stars Greg Jones Patch',
      '2004 Upper Deck Ultimate Collection /50 Luis Aparicio',
      '2005 Leaf Limited Bound by Round Jerseys Peyton Manning / Marvin Harrison PSA 7',
      '2006 Bowman Crown Jason Witten Refractor PSA 9',
      '2006 SP Authentic Tom Brady BGS 9',
      '2007 NFL Sweet Swatch Jersey Ted Ginn Jr.',
      '2007 Upper Deck Premier Penmanship Auto /75 Brandon Jackson',
      '2009-10 Upper Deck MJ Legacy Collection Gold Michael Jordan BCCG 10',
      "2010 Topps Anniversary Reprints Tom Brady '02 Topps CGC 9",
      '2012 Crown Royale Patch Auto /349 Dwayne Allen',
      '2013 Panini Cornerstones Russell Wilson',
      '2013-14 Panini Totally Certified Blue Signature Auto /10 Danny Green',
      '2014-15 Panini Threads Julius Randle Patch',
      '2015 Panini Prestige Auto /79 Danny Woodhead',
      '2015 Panini Contenders Rookie Patch Jamison Crowder',
      '2015 Panini Prizm Devin Booker PSA 9',
      '2016 Panini Black Gold Patch /199 Chris Moore',
      '2016 Panini Contenders Nate Sudfeld Auto',
      '2016 Panini Contenders Draft Picks Vernon Hargreaves III Auto',
      '2018 Panini Donruss Optic Rookie Phenom Kalen Ballage Patch',
      '2018 Panini Rookies & Stars Crusade Lamar Jackson PSA 9',
      '2018 Panini Prizm Silver Prizm Luka Doncic PSA 9',
      '2018 Panini Donruss Rookie Phenom Sam Darnold Patch',
      '2018 Panini Prizm Lamar Jackson PSA 9',
      '2018 Panini Prizm Trae Young PSA 10',
      '2018-19 Panini Donruss Significant Signatures Anfernee Simons',
      '2019 Bowman Mega Box Chrome Christian Santana PSA 10',
      '2019 Panini Absolute Spectrum Blue Patrick Mahomes II PSA 9',
      '2019-20 Panini Select Patch Auto /199 Sam Cassell',
      '2020 Panini Chronicles Omega Joe Burrow PSA 10',
      '2020 Panini Prizm Penmanship Caleb Martin Auto',
      '2020 Panini Select AJ Dillon Auto',
      '2020 Panini Chronicles Prestige Joe Burrow PSA 9',
      '2020 Panini Mosaic Justin Jefferson PSA 9',
      '2020 Panini Mosaic Patrick Mahomes II',
      '2020 Panini Select Premier Level Aaron Rodgers',
      '2020 Panini Select Die-Cut Red Prizm Patrick Mahomes II PSA 9',
      '2020 Panini Select Die-Cut Purple Prizm Jordan Love PSA 9',
      '2020 Topps Chrome Travis Lakins Auto',
      '2020 Donruss Elite Spellbound Anthony Edwards PSA 9',
      '2020 Panini Mosaic RC Auto CeeDee Lamb',
      '2020 Panini Prizm Jalen Hurts BGS 9.5',
      '2020 Panini Select Rookie Swatches Red Prizm Justin Herbert PSA 9',
      '2020-21 Panini Contenders Optic Perennial Nick Van Exel Auto',
      '2020-21 Panini Select Patch Auto /99 Precious Achiuwa',
      '2021 Panini Prizm Will Craig Auto',
      '2021 Panini Revolution Nikola Vucevic Auto',
      '2021 Panini Origins Patch Auto Simi Fehoko',
      '2021 Panini Prizm Draft Picks Payton Turner Auto',
      '2021 Topps Certified Game-Used Patch Auto /50 Brady Singer',
      '2021 Clearly Donruss The Rookies Trevor Lawrence PSA 10',
      '2021 Prizm Jalen Green PSA 10',
      '2021-22 Panini Donruss Elite /49 Draymond Green',
      '2022 Donruss Elite Series Rookies George Pickens PSA 10',
      '2022 Panini NBA Hoops Green Anthony Edwards PSA 8',
      "2022 Panini Select Rookie Patch Wan'Dale Robinson",
      '2022 Select Maroon Die-Cut Chet Holmgren PSA 9',
      '2022 Topps Chrome Julio Rodriguez',
      "2022 Topps Chrome McDonald's All American Jordan Walsh Auto",
      '2022 Topps Inception Rookies and Emerging Stars Auto /75 Emmanuel Rivera',
      '2022 Panini Prizm Frank Kaminsky Auto',
      '2022 Select Orange Prizm Desmond Ridder PSA 9',
      '2022-23 Panini Mosaic Thomas Bryant Auto',
      '2022-23 Panini Prizm Wilt Chamberlain',
      '2023 Panini Select Blue Patch Will Levis',
      '2023 Panini Elite Title Waves Green Patrick Mahomes II SGC 10',
      '2023 Revolution Shockwave Fractal Giannis Antetokounmpo PSA 10',
      '2023 Topps Chrome Bryce Johnson Auto',
      '2023 Topps Chrome Auto /250 Eddy Beltre',
      '2023 Topps Chrome David Villar Auto',
      '2023 Topps Finest Auto /99 Brett Baty',
      '2023 Bowman Chrome Prospects Purple Refractor Junior Caminero PSA 10',
      '2023 Mosaic Autograph Garrison Hearst PSA 9',
      '2023 Prizm Green Prizm Amen Thompson PSA 9',
      '2023-24 Donruss Optic /99 Donovan Mitchell',
      '2023-24 Panini Premium Stock Tyler Herro',
      '2023-24 Panini Prizm Penmanship Rashard Lewis Auto',
      '2023-24 Panini Contenders Double Patch Amen Thompson / Ausar Thompson',
      '2024 Bowman U Chrome Cameron Ward PSA 9',
      '2024 Donruss Optic Net Marvels Holo LeBron James PSA 9',
      '2024 Donruss Optic Blue Scope Drake Maye PSA 9',
      '2024 Panini Donruss Signature Series Auto Owen White',
      '2024 Panini Donruss Patrick Mahomes II Patch',
      '2024 Panini Donruss Jersey Kings Kyle Teel Patch',
      '2024 Panini Donruss Threads Derek Carr Patch',
      '2024 Panini Phoenix Auto /99 Tip Reiman',
      '2024 Panini Zenith Johnny Wilson Auto',
      '2024 Panini Zenith Z-Jersey Marvin Harrison Jr.',
      '2024 Panini Zenith Jersey Auto /199 Dallas Turner',
      '2024 Panini Absolute Auto /299 Kool-Aid McKinstry',
      '2024 Panini Luminance Will Shipley Auto',
      '2024 Panini Score Kellen Winslow Auto',
      '2024 Panini Select Patch Auto /199 Austin Jones',
      '2024 Panini Select Auto /99 Tyler Linderbaum',
      '2024 Prizm Black Sensational Signature Austin Reaves PSA 10',
      '2024 Select Green Disco Travon Walker PSA 9',
      '2024 Topps Chrome Drake Maye Auto',
      "2024 Topps Inception Certified Auto /125 Ja'Lynn Polk",
      '2024 Topps Chrome Auto /199 Cade Stover',
      '2024 Topps Chrome Base Autograph Variation /50 William Perry',
      '2024 Topps Finest Auto Tony Boselli',
      '2024 Topps Rookie Jersey Auto /75 Amari Bailey',
      '2024 Panini Select Caleb Williams',
      '2024 Prizm Ice Caitlin Clark PSA 9',
      '2024 Prizm Orange Ice Caitlin Clark PSA 9',
      '2024 Select Silver Prizm Jayden Daniels PSA 9',
      '2024 Topps Chrome Cosmic Black Eclipse Auto Tyler Soderstrom PSA 8',
      '2024 Topps Inception Rookie Auto Dallas Turner',
      '2024-25 Topps Chrome Gary Trent Jr. Auto',
      '2024-25 Panini Donruss Blue /299 Alex Caruso',
      '2024-25 Panini Prizm Anthony Davis',
      '2024-25 Panini Revolution /149 Naz Reid',
      '2024-25 Panini Donruss Luka Doncic',
      '2025 Panini Canton Certified Auto /99 Randy White',
      '2025 Panini Donruss Rookie Omarion Hampton Patch',
      '2025 Panini Donruss Optic /299 Trey McBride',
      '2025 Panini Mosaic Rookie Scripts Danny Stutsman Auto',
      '2025 Panini Phoenix Auto /99 Jihaad Campbell',
      '2025 Panini Auto /99 Kyshawn George',
      '2025 Panini Mosaic /199 Kurtis Rourke',
      '2025 Panini Mosaic Scripts Kayshon Boutte Auto',
      '2025 Panini Mosaic Red Prizm Shedeur Sanders SGC 9',
      '2025 Panini Mosaic Blue Orange /199 Tyrone Tracy Jr.',
      '2025 Panini Prizm Cam Skattebo',
      '2025 Panini Rookies and Stars /999 Puka Nacua',
      '2025 Topps Chrome Jaylin Williams Auto',
      '2025 Topps Chrome /25 Jordan Clarkson',
      '2025 Topps Finest Auto /150 Zebby Matthews',
      '2025 Topps Inception Auto Derrick White',
      '2025 Topps Power Players LeBron James',
      '2025 Panini Black Auto /199 Kyle McCord',
      '2025 Panini Certified RC Purple /299 Donovan Jackson',
      '2025 Panini Iconic Ink Auto /25 Cornelius Bennett',
      '2025 Panini Phoenix Rookie Phenom Patch Auto /199 Colston Loveland',
      '2025 Panini Prizm Draft Picks Rated Prospect Jeremiah Smith',
      '2025 Prizm Blue Wave Tyler Shough PSA 10',
      '2025 Select Neon Orange Pulsar Evan Engram PSA 9',
      '2025 Topps 8-Bit Ballers LeBron James',
      '2026 Topps Double Patch /199 Fernando Padilla',
      '2026 Topps Green Sparkle Nikola Jokic',
      '2026 Topps Inception /75 Tyler Herro',
    ],
  },
  {
    id: 'gauntlet-live-series-1-2026-07-28',
    title: 'Gauntlet Live Series 1 7/28/2026',
    subtitle: 'Exact 100-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-28',
    cards: [
      '2025 panini donruss optic /99 Derrick White',
      '2025 topps bowman /125 Sadiq White',
      '2025 topps midnight auto /199 Nique Clifford',
      '2025 topps chrome you quake Cooper Flagg',
      '2025 topps chrome generation rising Kon Knueppel',
      '2025 topps chrome rockstar Cooper Flagg',
      '2025 panini prizm /60 Zach Collins',
      '2025 panini prizm Stephon Castle',
      '2025 topps chrome voices Kon Knueppel',
      '2026 panini prizm /49 brilliance VJ Edgecombe',
      '2023 panini select blue Paolo Banchero',
      '2026 panini prizm /10 gold Cedric Coward',
      '2026 panini prizm /215 turq. Allen Iverson',
      '2025 panini mosaic /249 Khris Middleton',
      '2025 topps chrome McDonalds all American AJ Dybantsa',
      '2025 panini donruss optic my house Luka Doncic',
      '2026 panini prizm /99 Toni Kukoc',
      '2026 panini prizm break Giannis Antetokounmpo',
      '2026 topps /99 nba hoops Gary Payton II',
      '2025 panini prizm /75 red Aaron Nesmith',
      '2025 topps chrome /299 teal Grayson Allen',
      '2025 topps rookies Cooper Flagg',
      '2023 panini select /75 red/blue Nikola Jovic',
      '2022 panini select blue Chet Holmgren',
      '2025 topps rookies Cooper Flagg',
      '2024 silver prizm psa 10 Reed Sheppard',
      '2025 finest geometric psa 10 Kon Knueppel',
      '2023 prizm monopoly psa 10 Victor Wembanyama',
      '2026 topps finest /150 blue shimmer Mike Trout',
      '2026 panini prizm fifa /86 red Relebohile Mofokeng',
      '2026 topps chrome rc silver Munetaka Murakami',
      '2026 panini prizm fifa /215 rc orange Ahmed Hasan',
      '1989 score rookie psa 8 Barry Sanders',
      '2025 pokemon pflen ultra rare psa 10 Mega Charizard x EX',
      '2026 panini prizm fifa Virgil van Dijk',
      '2026 panini prizm fifa /299 purple Diego Gomez',
      '2026 panini prizm fifa Lionel Messi',
      '2026 panini prizm fifa /94 blue star Jearl Margaritha',
      '2023 disney lorcana en 2 enchanted psa 9 Pete',
      '2024 disney lorcana en 5 enchanted psa 8 Donald Duck',
      '2018 topps chrome pink refr. psa 10 Gleyber Torres',
      '2021 bowman draft sgc 9.5 prospect Gunnar Henderson',
      '2026 panini prizm fifa phenomenon Lionel Messi',
      '2025 topps finest fan auto Rob Lowe',
      '2026 topps chrome rc Munetaka Murakami',
      '2026 panini prizm fifa auto Jordan Ayew',
      '2020 panini mosaic center stage Baker Mayfield',
      '2022 panini luminance auto /100 Hassan Haskins',
      '1998 fleer flare showcase psa 10 row 3 Peyton Manning',
      '2020 panini mosaic red Tom Brady',
      '2025 panini donruss optic Luther Burden III',
      '2024 panini donruss optic /149 Terrion Arnold',
      '2025 panini donruss optic /99 pink Derek Carr',
      '2025 topps chrome Drake Maye',
      '2024 panini prizm Caleb Williams',
      '2015 panini crown royale /49 silhouettes Amari Cooper',
      '2025 topps chrome /25 red Denzel Burke',
      '2021 panini chronicles clear vision Trevor Lawrence',
      '2022 panini cert. piece of the game Erik Ezukanma',
      '2020 panini select die cut orange prizm psa 10 Justin Jefferson',
      '2021 panini donruss downtown Joe Namath',
      '2025 panini donruss optic rr Isaac TeSlaa',
      '2025 panini donruss optic /199 rr green Elic Ayomanor',
      '2025 topps chrome /275 Braelon Allen',
      '2025 panini donruss optic /15 purple Ed Reed',
      '2025 panini donruss optic /299 orange Jack Sawyer',
      '2025 topps chrome /250 purple Daniel Jones',
      '2025 topps chrome /299 rc Sebastian Castro',
      '2025 panini prizm silver Cam Skattebo',
      '2025 panini prizm Woody Marks',
      '2025 panini mosaic England games Caleb Williams',
      '2025 topps chrome blue Jalen Hurts',
      '2025 panini mosaic green/red Emeka Egbuka',
      '2025 panini prizm Saquon Barkley',
      '2025 topps chrome /99 green Jeremy Ruckert',
      '1988 topps psa 8 Joe Montana',
      '2025 topps comp auto /10 mix cd Corbin Carroll',
      '2024 topps pristine baseball Junior Caminero',
      '2025 panini phoenix ascension rookie jersey auto /49 Cam Skattebo',
      '2014 panini select auto Jordan Lynch',
      '2021 panini prizm auto /49 Elijah Moore',
      '2026 panini prizm auto /149 Sion James',
      '2025 panini phoenix auto Quinn Ewers',
      '2025 panini donruss auto signature series AJ Lawson',
      '2016 panini prime signatures /199 Tajae Sharpe',
      '2021 panini contenders draft picks auto Jaelan Phillips',
      '2021 panini elements auto /125 Elijah Moore',
      '2021 panini elements auto /125 Elijah Moore',
      '2018 panini luminance auto /249 Kalen Ballage',
      '2025 topps chrome black auto /150 Mason Graham',
      '2024 panini absolute kaboom sgc 9.5 Travis Kelce',
      '2024 panini disco prizm psa 9 Caleb Williams',
      '2021 prizm draft picks variation mojo prizm psa 10 Cade Cunningham',
      '2023 bowman draft sgc 10 Jackson Holliday',
      '2007 flare rookie sensations psa 7 Kevin Durant',
      '2018 panini prizm freshman phenoms psa 8 Shai Gilgeous Alexander',
      '2004 topps rookie psa 8 Eli Manning',
      '2021 select ecc. 9 Trevor Lawrence',
      '2019 panini contenders team logo auto psa 10 Diontae Johnson',
      '2023 prizm purple wave psa 8 TJ Hockenson',
    ],
  },
  {
    id: 'gauntlet-live-series-1-2026-07-27',
    title: 'Gauntlet Live Series 1 7/27/2026',
    subtitle: 'Exact 100-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-27',
    cards: [
      '1973 topps psa 4 Rod Carew',
      '1996 skybox premium psa 9 Kobe Bryant',
      '1996 topps finest streaks Clyde Drexler',
      "1998 Topps O'Neal / Mourning East-West PSA 10",
      '2011 topps triple threads patch auto /75 Kyle Rudolph',
      '2012 panini limited auto /349 Chandler Parsons',
      '2015 panini immaculate collection multi sport auto /25 Devin Booker',
      '2015 panini threads century proof red /99 sgc 7 LeBron James',
      '2016 panini spectra aspiring patch auto /199 Kenyan Drake',
      '2017 panini donruss optic rr psa 9 Deshaun Watson',
      '2018 panini prizm rc psa 10 Mikal Bridges',
      '2018 panini spectra /99 Jay Ajayi',
      '2018 panini status rc Jalen Brunson',
      '2019 bowman paper prospects psa 10 Joey Bart',
      '2019 panini absolute prem. materials /99 Damien Harris',
      '2019 panini mosaic prizm rc Tyler Herro',
      '2019 panini mosaic rc Zion Williamson',
      '2020 panini chronicles rookies and stars crusade Devin Vassell',
      '2020 panini contenders season ticket Adam Thielen',
      '2020 panini prizm rc Anthony Edwards',
      '2020 panini prizm rc Desmond Bane',
      '2020 panini prizm star gazing bgs 9.5 Mike Trout',
      '2020 panini select /75 Cam Akers',
      '2020 topps chrome bowman auto Will Holland',
      '2020 topps chrome psa 10 Luis Robert',
      '2021 bowman draft sgc 9.5 Gunnar Henderson',
      '2021 donruss elite ser.rk auto /75 psa 10 Trevor Lawrence',
      '2021 panini chronicles honors pink prizm sgc 9 Jonathan Kuminga',
      '2021 panini donruss optic Jaylen Waddle',
      '2021 panini donruss optic blue /179 Emmitt Smith',
      '2021 panini immaculate auto /60 clutch patch Ryan Jeffers',
      '2021 panini mosaic rc sgc 10 Jaylen Waddle',
      '2021 panini prizm DeVonta Smith',
      '2021 panini prizm donruss optic stars Marvin Jones Jr.',
      '2021 panini select orange flash prizm sgc 9.5 LeBron James',
      '2021 prizm blue yellow green choice psa 9 Tyler Herro',
      '2022 panini donruss vortex /50 Desmond Ridder',
      '2022 panini immaculate collection patch auto /49',
      '2022 panini prizm rookie spectra /10 Erik Ezukanma',
      '2022 panini score red zone auto Mike Williams',
      '2022 panini select draft picks /75',
      '2022 panini select prem. league unstoppable /10 Richarlison',
      '2023 bowman chrome prospect sgc 10',
      '2023 bowman draft sgc 9.5 Jackson Holliday',
      '2023 panini hoops great significance auto Mark Williams',
      '2023 panini phoenix scorched auto /25 Jerry Stackhouse',
      '2023 panini prizm /299 Hakeem Olajuwon',
      '2023 panini prizm select /175 Brandon Ingram',
      '2023 select silver prizm psa 9 Jayden Reed',
      '2023 topps bowman draft sgc 10 Jackson Holliday',
      '2023 topps chrome pink refr. fcg 9.5 Corbin Carroll',
      '2023 ultimate emblems hockey auto Cole McWard',
      '2024 donruss downtown psa 9 Tyreek Hill',
      '2024 prizm blue wave psa 9 Bo Nix',
      '2024 select red prizm psa 10 Josh Allen',
      '2024 topps chrome rookie auto refractor psa 9 Jackson Holliday',
      '2024 bowman U best ballers gold refr. psa 10 AJ Storr',
      '2024 fractal prizm psa 10 Caitlin Clark',
      '2024 panini donruss optic stars Maxx Crosby',
      '2024 panini illusions immortalized patch auto Kellen Winslow',
      '2024 panini mosaic purple /249 Paul George',
      '2024 panini mosaic rc Bronny James Jr.',
      '2024 panini prizm /175 Christian Braun',
      "2024 panini prizm contenders optic rookie ticket auto /30 Ja'Lynn Polk",
      '2024 panini rated rookie auto /150 Bucky Irving',
      '2024 score a treat rising stars pumpkin psa 9 Jayden Daniels',
      '2024 silver prizm psa 10 Jared McCain',
      '2024 topps bowman chrome auto /299 Naoyuki Uwasawa',
      '2024 topps chrome UPD aqua raywave psa 10 /199 Clayton Beeter',
      '2024 topps chrome UPD purple refr. auto /250 psa 8 Tanner Bibee',
      '2024 topps chrome auto Taylor Hendricks',
      '2024 topps chrome rookie auto refr. Julian Strawther',
      '2024 topps now rc psa 10 Jayden Daniels',
      '2024 ultimate emblems collection hockey auto Tristan Luneau',
      '2025 donruss optic orange rr psa 8 Tyler Warren',
      '2025 donruss wnba net marvels press proof psa 9 Paige Bueckers',
      '2025 panini donruss downtown Abdul Carter',
      '2025 panini donruss net marvels Derrick Rose',
      '2025 panini donruss optic /175 Spike Lee',
      '2025 panini donruss optic hashmarks auto JaMarcus Russell',
      '2025 panini donruss rr auto /99 Asa Newell',
      '2025 panini optic auto /25 Baron Davis',
      '2025 panini wnba prizm Angel Reese',
      '2025 topps archival auto /149 Nick Yorke',
      '2025 topps chrome auto /75 Luke Lachey',
      '2025 topps chrome green /99 Rashan Gary',
      '2025 topps finest /250 Bryce Young',
      '2025 topps finest auto Gordon Graceffo',
      '2025 topps midnight Victor Wembanyama',
      '2025 topps rc Kon Knueppel',
      '2026 panini prizm fifa Zinedine Zidane',
      '2026 panini prizm fifa alter ego Pelé',
      '2026 topps cert. legends auto Kevin Garnett',
      '2026 topps chrome black auto /75 Andres Gimenez',
      '2026 topps chrome hypernova Stephen Curry',
      '2026 topps chrome rc Munetaka Murakami',
      '2026 topps finest /99 Sandro Tonali',
      '2026 topps rc Cooper Flagg',
      'Emeka Egbuka sun',
      'Ronaldo Prizm Scorers Club',
    ],
  },
  {
    id: 'fusion-series-1-2026-07-27',
    title: 'Fusion Series 1 7/27/2026',
    subtitle: 'Exact 26-card checklist',
    seriesType: 'Fusion',
    date: '2026-07-27',
    cards: [
      '1996 Fleer Premier Decade of Excellence Michael Jordan PSA 9',
      '2019 Panini Mosaic MVPs LeBron James PSA 10',
      '2019 Panini Mosaic Pink Camo Prizm Giannis Antetokounmpo SGC 10',
      '2020 Panini Chronicles Honors RC Anthony Edwards SGC 10',
      '2020 Panini Donruss Rated Rookie LaMelo Ball',
      '2021 Panini One Jalen Green Auto /35',
      '2021 Panini Mosaic Reactive Josh Allen Orange PSA 10',
      '2022 Panini Flawless Excellence Auto /15 Jaylin Williams',
      '2022 Panini Prizm /100 Dwyane Wade',
      '2022 Panini Prizm Red /299 Giannis Antetokounmpo',
      '2022 Topps Chrome Prospect Bowman Auto /199 Patrick Baldwin Jr.',
      '2023 Panini Phoenix Thrillers /35 Paolo Banchero',
      '2023 Select Prizm RC Thunder Lane Scoot Henderson',
      '2024 Panini Donruss Optic Rated Rookie Stephon Castle',
      '2024 Panini Mosaic NBA Debut Gold Ron Holland II',
      '2024 Panini Obsidian Orbital /125 Giannis Antetokounmpo',
      '2024 Panini Prizm Black Sensational Signatures Auto Trayce Jackson-Davis',
      '2024 Panini Prizm Deca Auto Jaden Hardy',
      '2024 Panini Prizm Monopoly /299 Cody Williams',
      '2024 Panini Prizm Mosaic Red /299 Desmond Bane',
      '2025 Bowman Chrome Auto Derik Queen /150',
      '2025 Panini Donruss Jersey Series Patch Asa Newell',
      '2025 Panini Donruss Orange Auto /99 Baron Davis',
      '2026 Topps /199 Fred VanVleet',
      '2026 Topps Chrome Extraterrestrial /150 Kyshawn George',
      '2026 Topps Finest Auto Alex Sarr',
    ],
  },
  {
    id: 'limitless-series-1-2026-07-27',
    title: 'Limitless Series 1 7/27/2026',
    subtitle: 'Exact 24-card checklist',
    seriesType: 'Limitless',
    date: '2026-07-27',
    cards: [
      '1999 SP Signature Ricky Williams BCG 8.5',
      '2016 Panini Donruss Rated Rookie Press Proof',
      '2019 Hoops Premium Stock Flash RC Carsen Edwards PSA 10',
      '2019 Panini Luminance Auto /349 Rookie Ink Brian Burns',
      '2021 Panini Prizm Spectra /60 Blue Disco',
      '2021 Topps Chrome Prizm Refractor Mike Trout SGC 10',
      '2022 Panini Prizm Red Shai Gilgeous-Alexander',
      '2022 Panini Score Auto David Bell',
      '2022 Panini Select Draft Picks Trevor Lawrence',
      '2023 Bowman Draft Jackson Holliday SGC 10',
      '2023 Panini Score First Down Auto /10 Drew Sanders',
      '2023 Panini Select Prizm RC Auto /99 Jake Moody',
      '2024 Panini Donruss Downtown Terry Bradshaw',
      '2024 Panini Donruss Optic Rated Rookie Green Bo Nix',
      '2024 Panini Donruss Optic Uptowns Rome Odunze',
      '2024 Panini Prizm RC /99 Nate Wiggins',
      '2025 Panini Prizm RC Checkered Dillon Gabriel',
      '2025 Prizm Draft Dylan Raiola Manga',
      '2025 Topps Chrome RC Cam Ward',
      '2025 Topps Finest Oil Spill Rome Odunze',
      '2026 Panini Prizm FIFA Auto Ronald Koeman',
      '2026 Topps Chrome Bowman Wehiwa Aloy Auto',
      '2026 Topps Chrome RC Munetaka Murakami',
      '2026 Topps Chrome RC Munetaka Murakami',
    ],
  },
  {
    id: 'nova-series-1-2026-07-27',
    title: 'Nova Series 1 7/27/2026',
    subtitle: 'Exact 24-card checklist',
    seriesType: 'Nova',
    date: '2026-07-27',
    cards: [
      '2019 Panini Select RC A.J Brown',
      '2021 Donruss No Helmet Blue Press Proof Tom Brady SGC 9.5',
      '2022 Panini Score RC Auto Romeo Doubs',
      '2023 Panini Prizm Patrick Mahomes II',
      '2023 Panini Prizm Rookie Gear Patch Bijan Robinson',
      '2023 Prizm CJ Stroud Disco Prizm PSA 10',
      '2024 Panini Contenders Hall Pass /25 Dak Prescott',
      '2024 Panini Donruss Optic My House Patrick Mahomes II',
      '2024 Panini Phoenix Contours RC Caleb Williams',
      '2024 Panini Prizm /225 Kenneth Walker III',
      '2024 Panini Prizm Green Jayden Daniels',
      '2024 Panini Prizm Select RC Malik Nabers',
      '2025 Panini Donruss Downtown RC Shedeur Sanders',
      '2025 Panini Donruss Optic /199 Kyler Murray',
      '2025 Panini Donruss Optic /249 Zay Flowers',
      '2025 Panini Donruss Optic Jaxon Smith-Njigba',
      '2025 Panini Donruss Optic Best Tuddys Duo /25 Tua Tagovailoa & Jaylen Waddle',
      '2025 Panini Luminance Vestige CeeDee Lamb',
      '2025 Topps Chrome /250 Pink Tyreek Hill',
      '2025 Topps Chrome /50 RC Gold Sebastian Castro',
      '2025 Topps Chrome /75 Brock Bowers',
      '2025 Topps Chrome Blue Barry Sanders',
      '2025 Topps Chrome RC Auto /250 Kaleb Johnson',
      '2025 Topps Chrome /250 RC Auto Jaylen Reed',
    ],
  },
  {
    id: 'select-series-1-2026-07-27',
    title: 'Select Series 1 7/27/2026',
    subtitle: 'Exact 26-card checklist',
    seriesType: 'Select',
    date: '2026-07-27',
    cards: [
      '1999 Collectors Edge Auto /2110 Jeff Garcia',
      '1999 Fleer Mystique Fresh Ink /200',
      '2013 Panini Totally Certified RC Freshman Phenoms Auto /499',
      '2015 Topps Chrome RC Auto Matt Clark',
      '2016 Panini Contenders Championship Ticket Auto /99 Ricardo Louis Browns',
      '2016 Panini Prime Signatures Auto /99 Patch Dorial Green-Beckham',
      '2020 Panini Black Patch Auto /50 Antonio Gandy-Golden',
      '2020 Panini One Patch Auto /199 Cam Akers',
      '2021 Topps Certified Auto /249 Elvis Andrus',
      '2022 Panini Score Auto J.K Dobbins',
      '2023 Panini Phoenix Patch Auto /199 Jalen Wilson',
      '2024 Panini Absolute Kaboom Rome Odunze',
      '2024 Panini Contenders Rookie Ticket Auto Blake Corum',
      '2024 Panini Prizm Penmanship Auto Doug Collins',
      '2024 Topps Composite Auto /99 Willie Gault',
      '2025 Chrome RC Auto /25 Xavier Watts',
      '2025 Panini Donruss Optic Rated Rookie Auto /42 Ollie Gordon II',
      '2025 Panini Donruss Rated Rookie Auto Quinn Ewers',
      '2025 Panini Origins RC Auto TreVeyon Henderson',
      '2025 Panini Prizm Draft Picks Rp Auto Jeremiah Smith',
      '2025 Panini Score Auto Jalen McMillan',
      '2025 Panini Three and Two Auto /32 Paul Skenes',
      '2025 Topps Chrome Auto RJ Harvey',
      '2025 Topps Chrome Auto /499 Bucky Irving',
      '2025 Topps Chrome Patch Auto Dillon Gabriel',
      '2026 Topps Certified Rookie Class Chrome Auto Javon Small',
    ],
  },
  {
    id: 'gauntlet-series-1-2026-07-24',
    title: 'Gauntlet Series 1 7/24/2026',
    subtitle: 'Exact 100-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-24',
    cards: [
      '2025 topps chrome /99 Tyler Allgeier',
      "2025 topps chrome light speed /75 De'Von Achane",
      '2025 topps finest /20 TreVeyon Henderson',
      '2025 topps cert. auto /150 Courtland Sutton',
      '2025 topps chrome fortune /275 Malik Nabers',
      "2024 panini nat. treasures patch /35 Ja'Tavion Sanders",
      '2025 panini prizm donruss rookie Isaac TeSlaa',
      '2024 panini illusions rookie auto /299 Blake Corum',
      '2025 topps chrome starry nights Saquon Barkley',
      '2025 topps chrome starry nights Joe Burrow',
      '2025 panini contours RJ Harvey',
      '2025 topps chrome blue shimmer Jahmyr Gibbs',
      '2025 topps chrome starry nights Ashton Jeanty',
      '2025 panini optic Uptown Travis Hunter',
      '2024 topps chrome galaxy greats /99 Richard Sherman',
      '2025 panini silo. patch auto /99 Rod Smith',
      '2019 panini chronicles psa 10 Ja Morant',
      '2024 prizm orange ice psa 10 Michael Penix Jr.',
      '2019 panini prizm neon green pulsar psa 9 auto Alex Barnes',
      '1996 ultra decade of excellence psa 8 Michael Jordan',
      '1998 topps chrome seasons best refractor psa 9 Tim Duncan',
      '2024 bowmans best purple mojo psa 10 Aaron Judge',
      '2025 mosaic red camo psa 10 Jaxson Dart',
      '2026 topps bowman chrome auto Jean Carlos',
      '2026 topps bowman chrome auto Jean Carlos',
      '2026 topps finest oil spill Carter Jensen',
      '2026 topps finest personality auto Chris Rose',
      '2026 topps chrome auto Jared Jones',
      '2026 topps chrome auto /125 James Quinn Irons',
      '2024 panini select diamond level /25 Aaron Judge',
      '2025 panini donruss fifa Lionel Messi',
      '2026 topps Trey Gibson',
      '2023 select red disco psa 10 Brandon Miller',
      '2022 prizm draft picks var. purple ice prizm psa 10 Paolo Banchero',
      '2026 topps chrome extra terrestrial /75 Jalen Duren',
      '2026 topps chrome extra terrestrial /50 Chris Paul',
      '2026 topps chrome extra terr /99 Liam McNeeley',
      '2026 topps chrome green planet /75 Nikola Jokic',
      '2026 topps chrome space walk LeBron James',
      '2026 topps chrome extra terr. /75 Naz Reid',
      '2026 topps chrome extra terr. /99 Myles Turner',
      '2026 topps finest oil spill Brady House',
      '2021 panini clearly donruss auto sgc 10 Amon-Ra St. Brown',
      '2026 topps chrome bowman auto Moises Chace',
      '2025 topps finest auto Xavier Worthy',
      '2025 topps cert. auto Quinshon Judkins',
      '2026 topps bowman chrome auto Anderson Araujo',
      '2026 topps bowman chrome auto Andrew Tess',
      '2025 topps chrome red auto /5 Jaylin Williams',
      '2024 panini illusions duo rookie refl. auto Ray Davis & Issac G.',
      '2025 topps cert. signature auto Will Howard',
      '2025 topps finest purple /75 Drake Maye',
      '2024 panini illusions shining stars /99 Brock Purdy',
      '2024 panini illusions /399 Justin Jefferson',
      '2024 panini illusions /75 Terry Bradshaw',
      '2025 topps chrome blue Brian Thomas Jr.',
      '2024 panini illusions abracadabra /199 Jared Goff',
      '2025 panini phoenix color blast Tyler Shough',
      '2024 panini select prizm /81 Jahmyr Gibbs',
      '2025 topps chrome Elic Ayomanor',
      '2025 topps cert. pink /250 Cam Skattebo',
      '2024 panini illusions rc /299 Marvin Harrison',
      '2025 topps finest torcher /10 Tua Tagovailoa',
      '2025 topps cert. /100 rc Trevor Etienne',
      '2025 topps finest purple /99 Jayden Higgins',
      '2023 panini prizm gold shimmer Ray Allen',
      '2026 topps nba hoops LeBron James',
      '2024 panini donruss optic My House! Luka Doncic',
      '2024 panini prizm red Grant Williams',
      '2024 panini donruss optic rookie pink Reed Sheppard',
      '2025 topps chrome /199 Asa Newell',
      '2023 prizm deca dna cert. auto psa 9 Ja Morant',
      '1996 topps psa 9 Allen Iverson',
      '2023 donruss optic purple shock psa 10 rc Jaxon Smith-Njigba',
      '2024 prizm wnba psa 9 Caitlin Clark',
      '2023 prizm green ice psa 9 Bryce Young',
      '2024 panini prizm black /20 Klay Thompson',
      '2021 flawless gold legendary scripts auto /10 Oscar Robertson',
      '2026 topps bowman chrome auto Victor Arias',
      '2026 bowman chrome auto Anderson Araujo',
      '2025 bowman chrome buzz factor auto Braeden Shrewsberry',
      '2023 topps tier one auto /149 Pete Alonso',
      '2025 topps pirates /25 Paul Skenes',
      '2023 bowman chrome M/B psa 10 Spencer Jones',
      '2026 topps chrome auto Nick Monistere',
      '2023 panini prizm ufc Colby Covington',
      '2026 topps bowman chrome purple auto /250 Victor Arias',
      '2026 panini prizm fifa Alter Ego Luka Modric',
      '2026 topps finest auto /50 Jose Reyes',
      '2025 topps chrome starry nights Saquon Barkley',
      '2026 topps blue /150 Freddie Freeman',
      '2026 topps bowman chrome auto Ricardo Cova',
      '2025 topps cert. auto Quinshon Judkins',
      '2025 topps cert. auto rc Jaxon Dart',
      '2025 topps finest auto /99 Savion Williams',
      '2025 topps finest auto /99 Jalen Royals',
      '2025 panini donruss rr auto Dylan Sampson',
      '2024 panini prizm black prolific auto Jared McCain',
      '2024 optic holo auto Reed Sheppard',
      '2025 topps cert. auto rc Will Howard',
    ],
  },
  {
    id: 'gauntlet-live-series-2-2026-07-24',
    title: 'Gauntlet Live Series 2 7/24/2026',
    subtitle: 'Exact 100-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-24',
    cards: [
      '2025 topps chrome all etch psa 10 Aaron Judge',
      '2022 panini mosaic green aces Shohei Ohtani',
      '2026 topps chrome bowman sterling Shohei Ohtani',
      '2026 topps bowman chrome /399 Moises Chace',
      '2026 topps chrome black orange /25 CJ Kayfus',
      '2025 topps finest pink /200 Elly De La Cruz',
      '2026 topps chrome bowman /499 Riley Nelson',
      '2025 topps chrome pitcher/designated hitter Shohei Ohtani',
      '2026 topps chrome bowman /499 Daniel Hernandez',
      '2025 topps diamond icons auto /15 David Wright',
      '2018 topps cert. auto 5 star career Rafael Devers',
      '2025 topps chrome auto Quinshon Judkins',
      '2025 topps cert. auto Benjamin Morrison',
      '2025 topps finest auto rc Tez Johnson',
      '2022 panini flawless duo auto /15 Spencer Torkelson & Miguel Cab.',
      '2026 topps chrome rc auto /499 Christian Moore',
      '2026 topps chrome bowman auto /250 Hector Ramos',
      '2022 panini honors prizm rc auto /35 Garrett Wilson',
      '2025 topps cert. auto /25 Malaki Starks',
      '2024 panini one and one auto /35 Jared McCain',
      '2026 topps chrome xtra terr. /99 Payton Pritchard',
      '2026 topps chrome xtra terr. /150 Julius Randle',
      '2025 topps chrome green /99 Ryan Dunn',
      '2025 topps chrome pink /399 Jonas Valanciunas',
      '2024 panini national treasures Chet Holmgren',
      '2025 topps chrome patented Stephen Curry',
      '2024 panini donruss optic white hot rookies psa 10 Stephon Castle',
      '2025 topps chrome refractor Kon Knueppel',
      '2025 topps chrome hype legacy Caleb Wilson',
      '2025 topps chrome gold /50 Ivica Zubac',
      '2024 panini illusions patch immortalized auto /49 Drew Bledsoe',
      '2025 topps chrome blue /150 LeBron James',
      '2025 topps finest rc /92 Quinshon Judkins',
      '2025 panini prizm deca gold Paul George',
      '2024 panini illusion rookie /25 Malik Nabers',
      '2025 topps finest green /75 Omarion Hampton',
      '2023 panini flawless auto /25 Jalen Johnson',
      '2025 topps finest purple /150 Jared Goff',
      '2025 topps finest blue rc /250 Tetairoa McMillan',
      '2025 topps finest /200 Pete Crow-Armstrong',
      '2025 topps chrome rc wave Quinshon Judkins',
      '2017 leaf draft psa 10 Pat Mahomes II',
      '2025 panini prizm select auto /35 Roger Staubach',
      '2025 donruss optic prev. pink psa 10 Shedeur Sanders',
      '2025 topps chrome xtra terr. auto Will Howard',
      '2025 topps optic donruss blue hyper Will Howard',
      '2024 panini illusions /25 Ezekiel Elliott',
      '2021 panini obsidian Kyler Murray',
      '2025 topps cert. auto Benjamin Morrison',
      '2024 panini illusions abracadabra /399 Dak Prescott',
      '2025 topps comic court Court Flagg',
      '2025 topps finest purple /99 Travis Hunter',
      '2026 topps chrome hypernova Cade Cunningham',
      '2024 prizm wnba blue velocity psa 9 Caitlin Clark',
      '2025 topps cert. auto /25 Tommy Mellott',
      '2024 prizm black silver psa 8 Stephon Castle',
      '2025 topps cert. auto Dylan Sampson',
      '2026 topps space walk rc Cooper Flagg',
      '2025 topps finest blue /150 Brian Thomas Jr.',
      '2026 topps chrome purple /150 Reed Sheppard',
      '2025 topps bowman chrome anime Mike Trout',
      '2026 topps chrome bowman auto /150 Moises Chace',
      '2026 topps chrome black /99 Juan Soto',
      '2026 topps bowman chrome auto Edgar Montero',
      '2026 topps finest rc patch auto Colby Thomas',
      '2025 topps chrome rails and nails Shohei Ohtani',
      '2018 topps chrome 1983 topps psa 10 Aaron Judge',
      '2026 topps finest rc patch auto /99 Ryan Ritter',
      '2026 topps bowman chrome auto Handelfry Encarnacion',
      '2026 topps chrome bowman auto /499 Edgar Montero',
      '2025 panini national treasures auto /99 Shedeur Sanders',
      '2025 topps finest purple /75 Jalen Hurts',
      '2025 topps finest blue /75 Caleb Williams',
      '2025 topps finest purple /250 Josh Allen',
      '2025 topps finest purple /200 CJ Stroud',
      '2026 topps chrome black /25 CJ Kayfus',
      '2025 topps finest rc /200 Colston Loveland',
      '2025 topps finest blue /75 Bryce Young',
      '2024 panini illusions highlight swatches patch auto /99 Amon-Ra St. Brown',
      '2022 panini encased auto /10 rookie endorse Christian Watson',
      '2025 panini donruss gridiron marvels Justin Herbert',
      '2021 panini auto /75 patch freshman fabric Trevor Lawrence',
      '2024 panini illusions rc /499 Drake Maye',
      '2025 topps cert. pink /250 Drake Maye',
      '2025 topps finest rc auto Elic Ayomanor',
      '2025 topps finest rc auto Shemar Stewart',
      '2025 panini mosaic auto Shedeur Sanders',
      '2020 panini mosaic silver prizm psa 9 Tua Tagovailoa',
      '2024 panini illusions duo Aaron Rodgers & Garrett Wilson',
      '2024 panini immaculate auto /25 patch Jalen Ramsey',
      '2025 topps cert. auto /225 Drake Maye',
      '2025 topps cert. auto /225 Josh Jacobs',
      '2025 topps cert. auto Jack Bech',
      '2025 topps cert. auto /150 Tre Harris III',
      '2017 panini super bowl LI private signings auto psa 9 Brandin Cooks',
      '2025 topps finest auto /99 rc Jaylin Lane',
      '2024 panini illusion 1st impressions rc /249 Keon Coleman',
      '2024 panini illusions rookie endors auto /10 Adonai Mitchell',
      '2025 panini phoenix auto /199 Tyler Shough',
      '2022 panini flawless honored ink auto /15 Warren Moon',
    ],
  },
  {
    id: 'limitless-series-1-2026-07-24',
    title: 'Limitless Series 1 7/24/2026',
    subtitle: 'Exact 12-card checklist',
    seriesType: 'Limitless',
    date: '2026-07-24',
    cards: [
      '2018 Topps Update Legends In The Making PSA 10 Shohei Ohtani',
      '2025 Uptown PSA 9 Jaxson Dart',
      '2020 Prizm Draft Picks PSA 9 Javon Kinlaw',
      '2025 Topps Midnight PSA 9 David Robinson',
      '2025 Donruss PSA 10 Shedeur Sanders',
      '2022 Bowman PSA 10 Benny Montgomery',
      '2018 Topps Chrome PSA 9 Ronald Acuna Jr.',
      '2024 Donruss PSA 10 Michael Penix Jr.',
      '2017 Panini Score PSA 9 Patrick Mahomes II',
      '2019 Panini Select PSA 10 Kyler Murray',
      '2025 Pokemon Meg EN PSA 10 Mega Venusaur',
      '2024 Prizm WNBA PSA 9 Caitlin Clark',
    ],
  },
  {
    id: 'abyss-series-1-2026-07-24',
    title: 'Abyss Series 1 7/24/2026',
    subtitle: 'Exact 16-card checklist',
    seriesType: 'Abyss',
    date: '2026-07-24',
    cards: [
      '2020 Illusions Auto /10 Dan Marino',
      '2018 Select RPA /49 Saquon Barkley',
      '2026 Bowman Chrome Auto T.J. Rumfield',
      '2026 Bowman Chrome Auto T.J. Rumfield',
      '2025 Silhouette RPA /10 Avery Johnson',
      '2025 Signature /225 Dylan Sampson',
      '2025 Topps Chrome Auto Jarren Duran',
      '2026 Bowman Chrome Auto /499 Seojun Moon',
      '2025 Signature Auto /50 Kaden Prather',
      '2024 Panini Illusions /199 Ray Davis / Isaac Guerendo',
      '2026 Bowman Chrome Auto /100 Adrian Gil',
      '2022 Panini Prestige Auto /2 Drake London',
      '2026 Bowman Chrome Auto Charlie Condon',
      '2026 Bowman Chrome Auto Carter Jensen',
      '2026 Bowman Chrome Auto /299 Jack Wheeler',
      '2026 Bowman Chrome Gold Auto /75 Carlos Gutierrez',
    ],
  },
  {
    id: 'select-series-1-2026-07-24',
    title: 'Select Series 1 7/24/2026',
    subtitle: 'Exact 72-card checklist',
    seriesType: 'Select',
    date: '2026-07-24',
    cards: [
      '2024 Optic Holo Drake Maye',
      '2025 Optic Strong Arm /199 Ashton Jeanty',
      '2025 Optic Green /5 Rome Odunze',
      '2024 Prizm Deca Red /199 Bo Jackson',
      '2025 Topps Chrome Travis Hunter',
      '2025 Topps Chrome Green Lava /99 Jalen Hurts',
      '2025 Silhouette Super Bowl /49 Marcus Allen',
      '2025 Optic Black Pandora /149 Cam Skattebo',
      '2025 Topps Finest /150 Saquon Barkley',
      '2026 Bowman Chrome Electric Sluggers Shohei Ohtani',
      '2025 Topps Finest /125 Sam Darnold',
      '2025 Topps Chrome Auto /150 Spencer Steer',
      '2026 Topps Chrome Galaxy Greats /150 Kevin Garnett',
      '2025 Panini Phoenix Contours Ashton Jeanty',
      '2025 Donruss Bomb Squad Tyler Shough',
      '2025 Topps Finest Reflash /150 Drake Maye',
      '2026 Bowman Chrome Auto Seojun Moon',
      '2025 Signature Auto Will Howard',
      '2025 Topps Cosmic Starry Night Tetairoa McMillan',
      '2026 Bowman Chrome Auto /250 Matthew Ferrara',
      '2025 Topps Chrome Wave Tyler Shough',
      '2024 Panini Optical Illusions Luka Doncic / Jason Kidd',
      '2024 Panini Illusions Patch Auto /399 Ed McCaffrey',
      '2025 Topps Finest /99 Tetairoa McMillan',
      '2025 Topps Finest Auto Jaydon Blue',
      '2026 Topps Finest Auto /99 Trevor Hoffman',
      '2024 Panini Illusions RPA /199 Adonai Mitchell',
      '2025 Topps Cosmic Starry Night Tyler Warren',
      '2025 Topps Chrome Sapphire /10 Jaylen Reed',
      '2025 Inception RPA /25 Caleb Durbin',
      '2024 Panini Illusions Rookie Idols Faulk / Mitchell',
      '2024 Panini Illusions /399 Drake Maye',
      '2025 Topps Cosmic Starry Night Luther Burden III',
      '2025 Topps Chrome R/W/B Emeka Egbuka',
      '2025 Topps Finest /99 Omarion Hampton',
      '2025 Panini Phoenix Thunderbirds Bo Nix',
      '2025 Topps Chrome /199 Dalton Schultz',
      '2024 Panini Illusions Rookie Idols Brees / Rattler',
      '2025 Signature Gold /35 Geno Smith',
      '2025 Select R/W/B Cam Skattebo',
      '2026 Bowman Chrome Auto Roldy Brito',
      '2025 Topps Finest /250 Ashton Jeanty',
      '2024 Panini Illusions /299 Rome Odunze',
      '2025 Topps Finest /250 Luther Burden III',
      '2025 Optic Rookie Phenom Shedeur Sanders',
      '2025 National Treasures Patch /49 Lamar Jackson',
      '2024 Illusions Auto /99 Johnny Wilson',
      '2026 Topps Finest RPA /75 Kyle Teel',
      '2025 Topps Finest /325 Cam Skattebo',
      '2026 Bowman Chrome /250 Xavier Neyens',
      '2025 Topps Finest /250 Brock Bowers',
      '2025 Topps Finest /150 TreVeyon Henderson',
      '2025 Select R/W/B Travis Hunter',
      '2024 Panini Illusions /50 Saquon Barkley',
      '2020 Panini Immac Auto /25 Kyle Tucker',
      '2024 Panini Illusions Deja Vu /99 Chase / Johnson',
      '2025 Topps Chrome Shohei Ohtani',
      '2025 Topps Signature Auto RJ Harvey',
      '2022 Select Draft Picks Chris Olave',
      '2024 Illusions Rookie Idols McCaffrey / McCaffrey',
      '2024 Panini Illusions Deja Vu /199 Bland / Sanders',
      "2025 Topps Cosmic Starry Night Ja'Marr Chase",
      '2024 Panini Illusions Auto /299 Zaire Franklin',
      '2024 Panini Illusions RPA /199 Blake Corum',
      '2025 Topps Signature Auto /50 Jacory Croskey-Merritt',
      '2024 Panini Illusions RPA /249 Blake Corum',
      '2024 Panini Illusions Rookie Patch Brock Bowers',
      '2025 Topps Chrome Gold /50 Bo Jackson',
      '2025 Topps Finest /200 Travis Hunter',
      '2024 Donruss Downtown! Lamar Jackson',
      '2025 Topps Cosmic Planetarium CeeDee Lamb',
      '2025 Summit Triple Autographs /50 Rodgers / Stafford / Wilson',
    ],
  },
  {
    id: 'gauntlet-live',
    title: 'Gauntlet Live Series 1',
    subtitle: 'Exact 75-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-23',
    cards: [
      '1989 Hoops psa 9 Steve Kerr',
      '2021 Panini prizm chronicles Trevor Lawrence',
      '2022 Bowman Sapphire Shohei Ohtani psa 10',
      '2023 Panini impeccable rookie landscape auto /99 Jordan Addison',
      '2023 Panini select prizm Jimmy Butler',
      '2024 Panini donruss downtown Jordan Love',
      '2024 Panini donruss optic Lamar Jackson',
      '2024 Panini donruss prizm Nikola Jokic',
      '2024 Panini donruss rookie Brenden Rice',
      '2024 Panini prizm /199 Kyrie Irving',
      '2024 Panini prizm legends Karl Malone',
      '2024 Panini revolution prime time Tyrese Haliburton',
      '2025 Panini donruss optic Jahmyr Gibbs',
      '2025 Panini prizm Shedeur Sanders',
      '2025 Panini score Colston Loveland',
      '2025 Panini Select stained glass Antoine Griezmann',
      '2025 Topps /150 Nikola Jokic',
      '2025 Topps auto /25 Cam Whitmore',
      '2025 Topps base auto /50 variation Matthew Stafford',
      '2025 Topps Bowman chrome Kiyan Anthony',
      '2025 Topps chrome auto /499 Gradey Dick',
      '2025 Topps chrome /199 Walter Clayton Jr.',
      '2025 Topps chrome /275 gold Trae Young',
      '2025 Topps chrome /299 auto Chaz Lanier',
      '2025 Topps chrome /75 purple Alperen Sengun',
      '2025 Topps chrome Cam Ward',
      '2025 Topps chrome auto /150 Jacory Croskey-Merritt',
      '2025 Topps chrome auto /150 Paul Skenes',
      '2025 Topps chrome auto /199 black Jackson Jobe',
      '2025 Topps chrome auto /50 Nico Hoerner',
      '2025 Topps chrome auto /75 Tristan da Silva',
      '2025 Topps chrome auto Alex Sarr',
      '2025 Topps chrome auto Liam McNeeley',
      '2025 Topps chrome extraterrestrial Jaxon Dart',
      '2025 Topps chrome green wave /99 Xavier Legette',
      '2025 Topps chrome psa 9 Ace Bailey',
      '2025 Topps chrome starry nights Lamar Jackson',
      '2025 Topps finest /10 Quinn Ewers',
      '2025 Topps finest /150 Saquon Barkley',
      '2025 Topps finest /20 orange Jared Goff',
      '2025 Topps finest /200 Lamar Jackson',
      '2025 Topps finest /75 Luther Burden III',
      '2025 Topps finest auto David Justice',
      '2025 Topps finest auto Xavier Worthy',
      '2025 Topps finest fan auto /50 Mike Greenberg',
      '2025 Topps finest flashback auto Jared Verse',
      '2025 Topps flagship /10 Shai Gilgeous-Alexander',
      '2025 Topps fluidity Bijan Robinson',
      '2025 Topps inception auto /200 memorabilia Caden Dana',
      '2025 Topps inception auto /50 Alex Bregman',
      '2025 Topps midnight /35 Dirk Nowitzki',
      '2025 Topps midnight auto /199 Nique Clifford',
      '2025 Topps Now psa 10 Ohtani/Yamamoto/Sasaki',
      '2025 Topps reflash Caleb Williams',
      '2025 Topps rookie auto /499 Tyler Warren',
      '2026 Topps chrome auto /199 Owen Caissie',
      '2026 Panini prizm FIFA /215 Vinicius Jr.',
      '2026 Panini prizm FIFA /225 Blue wave Nahuel Molina',
      '2026 Panini prizm FIFA auto Andres Iniesta',
      '2026 Panini prizm FIFA national heroes auto /49',
      '2026 Topps auto /25 patch Adolis Garcia',
      '2026 Topps auto /50 Will Riley',
      '2026 Topps chrome /199 VJ Edgecombe',
      '2026 Topps chrome UFC auto Colby Covington',
      '2026 Topps chrome auto /150 Nelly Taylor',
      '2026 Topps chrome auto Breyson Guedez',
      '2026 Topps chrome black auto /199 Cade Horton',
      '2026 Topps chrome venus Luka Doncic',
      '2026 Topps finest /250 Nikola Jokic',
      '2026 Topps finest /275 Junior Caminero',
      '2026 Topps finest /350 Carter Bryant',
      '2026 Topps finest auto /199 Thomas Harrington',
      '2026 Topps finest of the millennium /150 Bukayo Saka',
      '2026 Topps finest of the millennium Lamine Yamal',
      '2026 Topps finest soccer Lamine Yamal',
    ],
  },
  {
    id: 'gauntlet-live-series-2',
    title: 'Gauntlet Live Series 2',
    subtitle: 'Exact 100-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-23',
    cards: [
      '1991 Topps auto /25 Scott Rolen',
      '2005 SP Authentic Michael Jordan PSA 9',
      '2017 Panini mosaic prizm auto /25 Karl-Anthony Towns',
      '2018 Panini Prizm Anfernee Simons Silver Prizm PSA 9',
      '2019 Bowman chrome draft Gunnar Henderson refractor sgc 10',
      '2019 Topps Bowman chrome auto Alejandro Kirk',
      '2020 Panini mosaic finals mvp Kevin Durant',
      '2020 Panini select CeeDee Lamb cut white prizm psa 9',
      '2020 Panini select sparks sig tri color prizm auto /49 psa 8 Jonathan Hernandez',
      '2021 Panini donruss optic Jaylen Waddle',
      '2021 Panini prizm UFC purple prizm psa 9 Holly Holm',
      '2021 Panini recon auto /5 Tyrese Maxey',
      '2022 Panini national treasures patch auto /99 Skyy Moore',
      '2022 Panini one precision auto Ahmad “Sauce” Gardner',
      '2022 Panini prizm draft picks Keegan Murray',
      '2022 Panini sensational sign. Auto Jaden Hardy',
      '2023 Panini donruss /99 Michael Porter Jr.',
      '2023 Panini donruss optic mythical Stefon Diggs',
      '2023 Panini select Keyonte George',
      '2024 Caitlin Clark collection donruss gold psa 9',
      '2024 prizm WNBA Caitlin Clark psa 9',
      '2024 donruss Panini psa 10 Tyreek Hill',
      '2024 Panini contenders optic rookie ticket Ricky Pearsall',
      '2024 Panini crown royale Kaboom Pau Gasol',
      '2024 Panini illusions /10 game magicians Dak Prescott',
      '2024 Panini select patch Alexandre Sarr',
      '2024 select prizm /49 Jayson Tatum',
      '2025 Bowman best univ. best of 2025 auto blue refr. psa 10 Kaidon Salter',
      '2025 Panini auto /99 Keyonte George',
      '2025 Bowman crystallized psa 10 Coby Mayo',
      '2025 chrome /10 Brooks Barnhizer',
      '2025 mosaic stained glass Cam Ward',
      '2025 Panini color blast Jalen Milroe',
      '2025 Panini donruss downtown Archie Manning',
      '2025 Panini donruss rookie Mason Taylor',
      '2025 Panini donruss rookie Travis Hunter',
      '2025 Panini impeccable rookie auto /49 Savion Williams',
      '2025 Panini mosaic prizm kaleidoscopic Puka Nacua',
      '2025 Panini rookie Omarion Hampton auto',
      '2025 Panini select Josh Allen',
      '2025 prizm draft picks purple ice psa 9 Arch Manning',
      '2025 Topps auto /225 Michael Pittman Jr.',
      '2025 Topps Bowman /99 Xavian Lee',
      '2025 Topps Bowman chrome gold /75 Pharrel Payne',
      '2025 Topps cert. auto Kaleb Johnson',
      '2025 Topps chrome /199 Dillon Brooks',
      '2025 Topps chrome /199 blue Justin Herbert',
      '2025 Topps chrome /25 Oso Ighodaro',
      '2025 Topps chrome /275 Bradley Beal',
      '2025 Topps chrome /275 Kristaps Porzingis',
      '2025 Topps chrome /50 Kaleb Johnson',
      '2025 Topps chrome /50 gold Cam Whitmore',
      '2025 Topps chrome /75 Collin Sexton',
      '2025 Topps chrome /75 Nick Smith Jr.',
      '2025 Topps chrome /75 extra terrestrial Breece Hall',
      '2025 Topps chrome LeBron James',
      '2025 Topps chrome Saquon Barkley',
      '2025 Topps chrome auto Omarion Hampton',
      '2025 Topps chrome auto /150 Aaron Nesmith',
      '2025 Topps chrome auto /150 Sarah Strong',
      '2025 Topps chrome auto /275 RJ Harvey',
      '2025 Topps chrome auto /50 Jayden Higgins',
      '2025 Topps chrome auto /50 Keon Coleman',
      '2025 Topps chrome auto Devin Carter',
      '2025 Topps chrome auto Will Richard',
      '2025 Topps chrome painted Dylan Harper',
      '2025 Topps chrome pink /250 George Kittle',
      '2025 Topps chrome starry nights Pat Surtain II',
      '2025 Topps chrome starry nights Tetairoa McMillan',
      '2025 Topps chrome urban legends Drake London',
      '2025 Topps chrome urban legends Jordan Love',
      '2025 Topps dual auto /25 Mark Fletcher Jr. & Carson Beck',
      '2025 Topps fanatical Travis Kelce',
      '2025 Topps fearless fighters auto /299 Brian Ortega',
      '2025 Topps finest /150 Luther Burden III',
      '2025 Topps finest /75 Sam LaPorta',
      '2025 Topps finest auto RJ Harvey',
      '2025 Topps finest flashback auto Ladd McConkey',
      '2025 Topps finest greats auto /99 Justin Tuck',
      '2025 Topps finest greats auto Vernon Davis',
      '2025 Topps finest reflash /50 Jared Verse',
      '2025 Topps finest refractor auto Tyler Warren',
      '2025 Topps rookie Cooper Flagg',
      '2026 Panini prizm /40 Santiago Gimenez',
      '2026 Panini prizm /94 Nicolas Tagliafico',
      '2026 Panini prizm auto Bernd Schneider',
      '2026 Panini prizm FIFA /86 Virgil van Dijk',
      '2026 Panini prizm FIFA /94 Ousmane Dembele',
      '2026 Panini prizm FIFA Emiliano Martinez',
      '2026 Panini prizm FIFA Ferran Torres',
      '2026 Panini prizm FIFA Miroslav Klose',
      '2026 Panini prizm FIFA auto /99 Federico Valverde',
      '2026 Topps chrome featherweight auto /25 Brian Ortega',
      '2026 Topps finest /150 Shaquille O’Neal',
      '2026 Topps finest /200 purple Anthony Davis',
      '2026 Topps home field Christian Moore',
      '2026 Topps midnight UFC auto Rose Namajunas',
      '2026 Topps rookie sign. Auto Joan Beringer',
      'JJ McCarthy stained glass psa 9',
      'Paul O’Neill Topps chrome black auto /150',
    ],
  },
  {
    id: 'gauntlet-live-series-3',
    title: 'Gauntlet Live Series 3 7/23/2026',
    subtitle: 'Exact 75-card checklist',
    seriesType: 'Gauntlet',
    date: '2026-07-23',
    cards: [
      '1986 donruss rookies Barry Bonds psa 9',
      '1989 Hoops Michael Jordan psa 9',
      '2000 Topps chrome power players refr. Jose Canseco psa 9',
      '2004 fleer auto /100 Ryan Howard',
      '2012 gridiron gems rookie /49 Mohamed Sanu',
      '2017 Panini donruss optic red/yellow psa 10 Donovan Mitchell',
      '2017 Panini donruss optic red/yellow psa 10 Lonzo Ball',
      '2018 Panini donruss press proof silver psa 9 Michael Porter Jr.',
      '2019 Panini mosaic reactive orange psa 9 Giannis Antetokounmpo',
      '2019 Panini prizm orange ice psa 9 Giannis Antetokounmpo',
      '2020 merlin chrome ucl u23 stars psa 10 Eduardo Camavinga',
      '2020 Panini chronicles classics psa 9 Justin Herbert',
      '2020 Panini prizm DP auto psa 10 Anthony McFarland Jr.',
      '2020 Panini prizm auto psa 9 Tony Jones Jr.',
      '2020 Panini prizm Joe Burrow',
      '2020 Panini prizm psa 7 Anthony Edwards',
      '2020 Panini select die cut purple prizm psa 9 Tua Tagovailoa',
      '2021 prizm draft picks green prizm psa 9 Mac Jones',
      '2021 prizm draft picks psa 9 all americans Kadarius Toney',
      '2021 prizm draft picks red white blue prizm psa 8 Najee Harris',
      '2021 prizm red wave auto /149 Elijah Moore',
      '2021 white mosaic psa 10 Alperen Sengun',
      '2023 donruss optic psa 9 Victor Wembanyama',
      '2023 Panini auto /10 TJ Dillashaw',
      '2023 Panini rookie Josh Minott',
      '2023 select tectonic psa 9 Brandon Miller',
      '2023 Topps all aces Shohei Ohtani',
      '2024 prizm Caitlin Clark kaleidoscopic psa 9',
      '2024 Panini donruss optic sign series auto Jaden Hardy',
      '2024 Panini immaculate coll. Sneaker /49 Rob Dillingham',
      '2024 Panini mosaic auto Dillon Jones',
      '2024 Topps chrome rookie auto psa/dna cert. Wyatt Langford psa 10',
      '2025 Topps chrome starry nights Myles Garrett',
      '2025 Panini Mosaic Football Shedeur Sanders',
      '2025 Topps Chrome VJ Edgecombe x-fractor psa 8',
      '2025 Panini donruss downtown Matthew Golden',
      '2025 Panini prizm Colston Loveland',
      '2025 Panini select Cam Ward',
      '2025 Panini select Nick Emmanwori',
      '2025 Panini select Shedeur Sanders',
      '2025 Panini select zebra Jayden Higgins',
      '2025 Panini stars Omarion Hampton',
      '2025 Topps /150 Bijan Robinson',
      '2025 Topps 1990 relic memorabilia 35 anniv. George Springer',
      '2025 Topps 5 star pentamerous penmanship auto /25 Mark Teixeira',
      '2025 Topps Devin Booker anime',
      '2025 Topps auto Ayla McDowell',
      '2025 Topps Bowman chrome /25 Deniya Prawl',
      '2025 Topps Bowman chrome auto Coen Carr',
      '2025 Topps chrome /150 greatest loading Cedric Coward',
      '2025 Topps chrome /50 Joan Beringer',
      '2025 Topps chrome Ace Bailey',
      '2025 Topps chrome Ashton Jeanty',
      '2025 Topps chrome Cooper Flagg',
      '2025 Topps chrome Jeremy Ruckert',
      '2025 Topps chrome Kon Knueppel',
      '2025 Topps chrome Noa Essengue',
      '2025 Topps chrome Yang Hansen',
      '2025 Topps chrome auto Kel’el Ware',
      '2025 Topps chrome camo Calvin Ridley',
      '2025 Topps chrome fortune Ashton Jeanty',
      '2025 Topps chrome purple refractor psa 8 Tyrese Proctor',
      '2025 Topps chrome starry night CeeDee Lamb',
      '2025 Topps chrome starry nights Cam Ward',
      '2025 Topps chrome starry nights Emeka Egbuka',
      '2025 Topps chrome starry nights Ja’Marr Chase',
      '2025 Topps finest auto Chase Brown',
      '2025 Topps finest auto Mason Miller',
      '2025 Topps finest auto Riley Leonard',
      '2025 Topps finest greats auto /99 Darren Sproles',
      '2025 Topps rookie horiz. Midnight auto Asa Newell',
      '2026 Panini prizm FIFA Mohamed Salah',
      '2026 Topps chrome /175 Karl-Anthony Towns',
      '2026 Topps chrome /250 Charles Oliveira',
      '2026 Topps worlds finest Clayton Kershaw',
    ],
  },
];
